// {{ .Project }}/tdesign-vue3-mobile/src/components/LoginAccountInput.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, onUpdated, ref, useId, watch } from 'vue';
import { clearLoginAccountHistory, loginAccountHistory, removeLoginAccount } from '../lib/storage';
import { t } from '../locales';
const model = defineModel<string>({ required: true });
const emit = defineEmits<{ blur: [value: string]; select: [] }>();
const root = ref<HTMLElement>();
const identity = useId();
const focused = ref(false);
const active = ref(-1);
const history = ref(loginAccountHistory());
const items = computed(() => {
  const query = model.value.trim().toLowerCase();
  return history.value.filter((account) => account.toLowerCase().includes(query));
});
watch(model, () => {
  active.value = -1;
});
function syncInput() {
  const input = root.value?.querySelector('input');
  if (!input) return;
  input.setAttribute('role', 'combobox');
  input.setAttribute('aria-autocomplete', 'list');
  input.setAttribute('aria-expanded', String(focused.value && history.value.length > 0));
  input.setAttribute('aria-controls', `${identity}-accounts`);
  input.setAttribute('autocapitalize', 'none');
  input.setAttribute('spellcheck', 'false');
  if (active.value >= 0 && focused.value)
    input.setAttribute('aria-activedescendant', `${identity}-account-${active.value}`);
  else input.removeAttribute('aria-activedescendant');
}
onMounted(syncInput);
onUpdated(syncInput);
async function pick(value: string) {
  model.value = value;
  root.value?.querySelector('input')?.focus();
  focused.value = false;
  active.value = -1;
  emit('select');
  await nextTick();
  emit('blur', value);
}
function clearHistory() {
  history.value = clearLoginAccountHistory();
  root.value?.querySelector('input')?.focus();
  focused.value = false;
  active.value = -1;
}
function focus() {
  history.value = loginAccountHistory();
  focused.value = true;
}
function leave(event: FocusEvent) {
  if (root.value?.contains(event.relatedTarget as Node | null)) return;
  focused.value = false;
  active.value = -1;
  emit('blur', model.value);
}
function keydown(event: KeyboardEvent) {
  if (event.isComposing || !(event.target instanceof HTMLInputElement)) return;
  if (event.key === 'Escape') {
    event.preventDefault();
    focused.value = false;
    active.value = -1;
  } else if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
    event.preventDefault();
    focused.value = true;
    if (!items.value.length) return;
    active.value =
      active.value < 0
        ? event.key === 'ArrowDown'
          ? 0
          : items.value.length - 1
        : (active.value + (event.key === 'ArrowDown' ? 1 : -1) + items.value.length) %
          items.value.length;
    void nextTick(() =>
      document
        .getElementById(`${identity}-account-${active.value}`)
        ?.scrollIntoView({ block: 'nearest' }),
    );
  } else if (
    event.key === 'Enter' &&
    focused.value &&
    active.value >= 0 &&
    items.value[active.value]
  ) {
    event.preventDefault();
    event.stopPropagation();
    void pick(items.value[active.value]!);
  }
}
function segments(value: string) {
  const query = model.value.trim();
  const index = query ? value.toLowerCase().indexOf(query.toLowerCase()) : -1;
  return index < 0
    ? [{ text: value, match: false }]
    : [
        { text: value.slice(0, index), match: false },
        { text: value.slice(index, index + query.length), match: true },
        { text: value.slice(index + query.length), match: false },
      ];
}
</script>
<template>
  <div
    ref="root"
    class="search-field login-account-field"
    @focusout="leave"
    @keydown.capture="keydown"
  >
    <t-input
      id="username"
      v-model="model"
      name="username"
      autocomplete="off"
      :placeholder="t('app.validation.username')"
      clearable
      @update:model-value="
        focused = true;
        active = -1;
      "
      @focus="focus"
    />
    <div
      v-if="focused && history.length"
      class="suggestions card account-suggestions"
      @mousedown.prevent
    >
      <div class="account-history-heading">
        <small>{{ t('loginAccountHistory') }}</small
        ><button type="button" @click="clearHistory">{{ t('clearLoginAccountHistory') }}</button>
      </div>
      <div :id="`${identity}-accounts`" role="listbox" :aria-label="t('loginAccountHistory')">
        <p v-if="!items.length" class="account-history-empty">
          {{ t('loginAccountHistoryEmpty') }}
        </p>
        <div
          v-for="(value, index) in items"
          :key="value"
          class="suggestion-row"
          :class="{ 'account-active': active === index }"
        >
          <button
            :id="`${identity}-account-${index}`"
            type="button"
            role="option"
            :aria-selected="active === index"
            @click="pick(value)"
          >
            <template v-for="(segment, part) in segments(value)" :key="part"
              ><mark v-if="segment.match">{{ segment.text }}</mark
              ><template v-else>{{ segment.text }}</template></template
            >
          </button>
          <button
            type="button"
            :aria-label="t('system.suggestions.removeHistory', { value })"
            @click="
              history = removeLoginAccount(value);
              active = -1;
            "
          >
            ×
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// {{ .Project }}/tail-react/src/components/auth/LoginAccountInput.tsx
import Input from "@/components/form/input/InputField";
import { CloseLineIcon } from "@/icons";
import {
  readLoginAccountHistory,
  writeLoginAccountHistory,
} from "@/utils/loginAccountHistory";
import { useEffect, useState, type KeyboardEvent } from "react";
import { useTranslation } from "react-i18next";

interface LoginAccountInputProps {
  error?: string;
  onBlur: () => void;
  onChange: (value: string) => void;
  value: string;
}

export default function LoginAccountInput({
  error,
  onBlur,
  onChange,
  value,
}: LoginAccountInputProps) {
  const { t } = useTranslation();
  const [history, setHistory] = useState(readLoginAccountHistory);
  const [open, setOpen] = useState(false);
  const [activeIndex, setActiveIndex] = useState(-1);
  const showHistory = open && history.length > 0;
  const query = value.trim().toLowerCase();
  const options = history.filter((item) => item.toLowerCase().includes(query));
  useEffect(() => {
    if (open && activeIndex >= 0)
      document
        .getElementById(`login-account-option-${activeIndex}`)
        ?.scrollIntoView({ block: "nearest" });
  }, [activeIndex, open]);
  const select = (account: string) => {
    onChange(account);
    setOpen(false);
    setActiveIndex(-1);
  };
  const updateHistory = (accounts: string[]) => {
    setHistory(writeLoginAccountHistory(accounts));
    setActiveIndex(-1);
  };
  const handleKeyDown = (event: KeyboardEvent<HTMLInputElement>) => {
    if (event.nativeEvent.isComposing) return;
    if (event.key === "ArrowDown" || event.key === "ArrowUp") {
      event.preventDefault();
      setOpen(true);
      if (options.length)
        setActiveIndex((index) =>
          event.key === "ArrowDown"
            ? (index + 1) % options.length
            : index <= 0
              ? options.length - 1
              : index - 1,
        );
    } else if (event.key === "Enter" && open && options[activeIndex]) {
      event.preventDefault();
      select(options[activeIndex]);
    } else if (event.key === "Escape" && open) {
      event.preventDefault();
      setOpen(false);
      setActiveIndex(-1);
    }
  };

  return (
    <div
      className="relative"
      onBlur={(event) => {
        if (!event.currentTarget.contains(event.relatedTarget)) {
          setOpen(false);
          setActiveIndex(-1);
          onBlur();
        }
      }}
    >
      <Input
        id="signin-username"
        name="username"
        autoComplete="off"
        role="combobox"
        aria-autocomplete="list"
        aria-expanded={showHistory}
        aria-controls={showHistory ? "login-account-options" : undefined}
        aria-activedescendant={
          showHistory && options[activeIndex]
            ? `login-account-option-${activeIndex}`
            : undefined
        }
        aria-invalid={Boolean(error)}
        aria-describedby={error ? "signin-username-error" : undefined}
        error={Boolean(error)}
        placeholder={t("auth.username")}
        value={value}
        onFocus={() => {
          setOpen(true);
          setActiveIndex(-1);
        }}
        onChange={(event) => {
          onChange(event.target.value);
          setOpen(true);
          setActiveIndex(-1);
        }}
        onKeyDown={handleKeyDown}
      />
      {showHistory && (
        <div className="absolute z-50 mt-1 max-h-72 w-full overflow-auto rounded-xl border border-gray-200 bg-white p-2 shadow-theme-lg dark:border-gray-700 dark:bg-gray-900">
          <div className="flex items-center justify-between gap-2 px-2 py-1">
            <p className="text-xs font-medium text-gray-400">
              {t("auth.accountHistory")}
            </p>
            {history.length > 0 && (
              <button
                className="rounded px-1 text-xs text-gray-500 hover:text-error-500 dark:text-gray-400"
                type="button"
                onMouseDown={(event) => event.preventDefault()}
                onClick={() => updateHistory([])}
              >
                {t("auth.clearAccountHistory")}
              </button>
            )}
          </div>
          <div
            id="login-account-options"
            role="listbox"
            aria-label={t("auth.accountHistory")}
          >
            {options.map((item, index) => (
              <div
                id={`login-account-option-${index}`}
                role="option"
                aria-selected={index === activeIndex}
                key={item}
                className={`flex items-center rounded-lg hover:bg-gray-100 dark:hover:bg-white/5 ${index === activeIndex ? "bg-gray-100 dark:bg-white/5" : ""}`}
              >
                <button
                  className="min-w-0 flex-1 truncate rounded-md px-2 py-2 text-start text-sm text-gray-700 dark:text-gray-300"
                  type="button"
                  onMouseDown={(event) => event.preventDefault()}
                  onClick={() => select(item)}
                >
                  <Highlighted value={item} query={query} />
                </button>
                <button
                  aria-label={t("auth.removeAccountHistory", { value: item })}
                  className="me-1 rounded p-1 text-gray-400 hover:text-error-500"
                  type="button"
                  onMouseDown={(event) => event.preventDefault()}
                  onClick={() =>
                    updateHistory(history.filter((account) => account !== item))
                  }
                >
                  <CloseLineIcon className="size-4" />
                </button>
              </div>
            ))}
          </div>
          {options.length === 0 && (
            <p
              role="status"
              className="px-2 py-3 text-sm text-gray-500 dark:text-gray-400"
            >
              {t("auth.noMatchingAccounts")}
            </p>
          )}
        </div>
      )}
      {error && (
        <p
          id="signin-username-error"
          role="alert"
          className="mt-1.5 text-xs text-error-500"
        >
          {error}
        </p>
      )}
    </div>
  );
}

function Highlighted({ query, value }: { query: string; value: string }) {
  const index = value.toLowerCase().indexOf(query);
  if (!query || index < 0) return value;
  return (
    <>
      {value.slice(0, index)}
      <mark className="bg-transparent font-semibold text-error-500">
        {value.slice(index, index + query.length)}
      </mark>
      {value.slice(index + query.length)}
    </>
  );
}
