// {{ .Project }}/shadcn-react/src/features/auth/components/login-account-input.tsx
'use client';

import { Icons } from '@/components/icons';
import { Input } from '@/components/ui/input';
import { useLocale } from '@/features/i18n/locale-context';
import { cn } from '@/lib/utils';
import * as React from 'react';
import { readLoginAccountHistory, writeLoginAccountHistory } from '../account-history';

interface LoginAccountInputProps {
  error?: string;
  onChange: (value: string) => void;
  value: string;
}

export function LoginAccountInput({ error, onChange, value }: LoginAccountInputProps) {
  const { pick } = useLocale();
  const [history, setHistory] = React.useState<string[]>([]);
  const [open, setOpen] = React.useState(false);
  const [activeIndex, setActiveIndex] = React.useState(-1);
  const showHistory = open && history.length > 0;
  React.useEffect(() => {
    // oxlint-disable-next-line react/set-state-in-effect -- hydrate browser-only login account history after mount
    setHistory(readLoginAccountHistory());
  }, []);
  const query = value.trim().toLowerCase();
  const options = history.filter((item) => item.toLowerCase().includes(query));
  React.useEffect(() => {
    if (open && activeIndex >= 0)
      document
        .getElementById(`login-account-option-${activeIndex}`)
        ?.scrollIntoView({ block: 'nearest' });
  }, [activeIndex, open]);
  const select = (account: string) => {
    onChange(account);
    setOpen(false);
    setActiveIndex(-1);
  };
  const updateHistory = (accounts: string[]) => {
    setHistory(writeLoginAccountHistory(accounts));
    setActiveIndex(-1);
  };
  const handleKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.nativeEvent.isComposing) return;
    if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
      event.preventDefault();
      setOpen(true);
      if (options.length)
        setActiveIndex((index) =>
          event.key === 'ArrowDown'
            ? (index + 1) % options.length
            : index <= 0
              ? options.length - 1
              : index - 1
        );
    } else if (event.key === 'Enter' && open && options[activeIndex]) {
      event.preventDefault();
      select(options[activeIndex]);
    } else if (event.key === 'Escape' && open) {
      event.preventDefault();
      setOpen(false);
      setActiveIndex(-1);
    }
  };
  return (
    <div
      className='relative'
      onBlur={(event) => {
        if (!event.currentTarget.contains(event.relatedTarget)) {
          setOpen(false);
          setActiveIndex(-1);
        }
      }}
    >
      <Input
        id='username'
        name='username'
        role='combobox'
        autoComplete='off'
        aria-autocomplete='list'
        aria-expanded={showHistory}
        aria-controls={showHistory ? 'login-account-options' : undefined}
        aria-activedescendant={
          showHistory && options[activeIndex] ? `login-account-option-${activeIndex}` : undefined
        }
        aria-invalid={Boolean(error)}
        aria-describedby={error ? 'username-error' : undefined}
        placeholder={pick('Username', '用户名')}
        value={value}
        onFocus={() => {
          setOpen(true);
          setActiveIndex(-1);
        }}
        onChange={(event) => {
          onChange(event.target.value);
          setOpen(true);
          setActiveIndex(-1);
        }}
        onKeyDown={handleKeyDown}
      />
      {showHistory && (
        <div className='absolute z-50 mt-1 max-h-80 w-full overflow-y-auto rounded-lg border bg-popover p-1 text-popover-foreground shadow-md'>
          <div className='flex items-center justify-between gap-2 px-2 py-1.5'>
            <p className='text-xs font-medium text-muted-foreground'>
              {pick('Login account history', '历史登录账号')}
            </p>
            {history.length > 0 && (
              <button
                className='rounded px-1 text-xs text-muted-foreground hover:text-destructive'
                type='button'
                onMouseDown={(event) => event.preventDefault()}
                onClick={() => updateHistory([])}
              >
                {pick('Clear history', '清空历史')}
              </button>
            )}
          </div>
          <div
            id='login-account-options'
            role='listbox'
            aria-label={pick('Login account history', '历史登录账号')}
          >
            {options.map((item, index) => (
              <div
                key={item}
                id={`login-account-option-${index}`}
                role='option'
                aria-selected={index === activeIndex}
                className={cn(
                  'flex items-center rounded-md hover:bg-accent',
                  index === activeIndex && 'bg-accent'
                )}
              >
                <button
                  className='min-w-0 flex-1 truncate rounded-md px-2 py-2 text-start text-sm'
                  type='button'
                  onMouseDown={(event) => event.preventDefault()}
                  onClick={() => select(item)}
                >
                  <Highlighted value={item} query={query} />
                </button>
                <button
                  aria-label={pick(`Remove ${item} from history`, `从历史记录中移除“${item}”`)}
                  className='me-1 rounded p-1 text-muted-foreground hover:bg-muted hover:text-foreground'
                  type='button'
                  onMouseDown={(event) => event.preventDefault()}
                  onClick={() => updateHistory(history.filter((account) => account !== item))}
                >
                  <Icons.close className='size-3.5' />
                </button>
              </div>
            ))}
          </div>
          {options.length === 0 && (
            <p role='status' className='px-2 py-3 text-sm text-muted-foreground'>
              {pick('No matching accounts', '没有匹配的账号')}
            </p>
          )}
        </div>
      )}
    </div>
  );
}

function Highlighted({ query, value }: { query: string; value: string }) {
  const index = value.toLowerCase().indexOf(query);
  if (!query || index < 0) return value;
  return (
    <>
      {value.slice(0, index)}
      <mark className='bg-transparent font-semibold text-destructive'>
        {value.slice(index, index + query.length)}
      </mark>
      {value.slice(index + query.length)}
    </>
  );
}

// {{ .Project }}/tdesign-vue3-mobile/src/components/LoginAccountInput.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, onUpdated, ref, useId, watch } from 'vue';
import { clearLoginAccountHistory, loginAccountHistory, removeLoginAccount } from '../lib/storage';
import { t } from '../locales';
const model = defineModel<string>({ required: true });
const emit = defineEmits<{ blur: [value: string]; select: [] }>();
const root = ref<HTMLElement>();
const identity = useId();
const focused = ref(false);
const active = ref(-1);
const history = ref(loginAccountHistory());
const items = computed(() => {
  const query = model.value.trim().toLowerCase();
  return history.value.filter((account) => account.toLowerCase().includes(query));
});
watch(model, () => {
  active.value = -1;
});
function syncInput() {
  const input = root.value?.querySelector('input');
  if (!input) return;
  input.setAttribute('role', 'combobox');
  input.setAttribute('aria-autocomplete', 'list');
  input.setAttribute('aria-expanded', String(focused.value && history.value.length > 0));
  input.setAttribute('aria-controls', `${identity}-accounts`);
  input.setAttribute('autocapitalize', 'none');
  input.setAttribute('spellcheck', 'false');
  if (active.value >= 0 && focused.value)
    input.setAttribute('aria-activedescendant', `${identity}-account-${active.value}`);
  else input.removeAttribute('aria-activedescendant');
}
onMounted(syncInput);
onUpdated(syncInput);
async function pick(value: string) {
  model.value = value;
  root.value?.querySelector('input')?.focus();
  focused.value = false;
  active.value = -1;
  emit('select');
  await nextTick();
  emit('blur', value);
}
function clearHistory() {
  history.value = clearLoginAccountHistory();
  root.value?.querySelector('input')?.focus();
  focused.value = false;
  active.value = -1;
}
function focus() {
  history.value = loginAccountHistory();
  focused.value = true;
}
function leave(event: FocusEvent) {
  if (root.value?.contains(event.relatedTarget as Node | null)) return;
  focused.value = false;
  active.value = -1;
  emit('blur', model.value);
}
function keydown(event: KeyboardEvent) {
  if (event.isComposing || !(event.target instanceof HTMLInputElement)) return;
  if (event.key === 'Escape') {
    event.preventDefault();
    focused.value = false;
    active.value = -1;
  } else if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
    event.preventDefault();
    focused.value = true;
    if (!items.value.length) return;
    active.value =
      active.value < 0
        ? event.key === 'ArrowDown'
          ? 0
          : items.value.length - 1
        : (active.value + (event.key === 'ArrowDown' ? 1 : -1) + items.value.length) %
          items.value.length;
    void nextTick(() =>
      document
        .getElementById(`${identity}-account-${active.value}`)
        ?.scrollIntoView({ block: 'nearest' }),
    );
  } else if (
    event.key === 'Enter' &&
    focused.value &&
    active.value >= 0 &&
    items.value[active.value]
  ) {
    event.preventDefault();
    event.stopPropagation();
    void pick(items.value[active.value]!);
  }
}
function segments(value: string) {
  const query = model.value.trim();
  const index = query ? value.toLowerCase().indexOf(query.toLowerCase()) : -1;
  return index < 0
    ? [{ text: value, match: false }]
    : [
        { text: value.slice(0, index), match: false },
        { text: value.slice(index, index + query.length), match: true },
        { text: value.slice(index + query.length), match: false },
      ];
}
</script>
<template>
  <div
    ref="root"
    class="search-field login-account-field"
    @focusout="leave"
    @keydown.capture="keydown"
  >
    <t-input
      id="username"
      v-model="model"
      name="username"
      autocomplete="off"
      :placeholder="t('app.validation.username')"
      clearable
      @update:model-value="
        focused = true;
        active = -1;
      "
      @focus="focus"
    />
    <div
      v-if="focused && history.length"
      class="suggestions card account-suggestions"
      @mousedown.prevent
    >
      <div class="account-history-heading">
        <small>{{ t('loginAccountHistory') }}</small
        ><button type="button" @click="clearHistory">{{ t('clearLoginAccountHistory') }}</button>
      </div>
      <div :id="`${identity}-accounts`" role="listbox" :aria-label="t('loginAccountHistory')">
        <p v-if="!items.length" class="account-history-empty">
          {{ t('loginAccountHistoryEmpty') }}
        </p>
        <div
          v-for="(value, index) in items"
          :key="value"
          class="suggestion-row"
          :class="{ 'account-active': active === index }"
        >
          <button
            :id="`${identity}-account-${index}`"
            type="button"
            role="option"
            :aria-selected="active === index"
            @click="pick(value)"
          >
            <template v-for="(segment, part) in segments(value)" :key="part"
              ><mark v-if="segment.match">{{ segment.text }}</mark
              ><template v-else>{{ segment.text }}</template></template
            >
          </button>
          <button
            type="button"
            :aria-label="t('system.suggestions.removeHistory', { value })"
            @click="
              history = removeLoginAccount(value);
              active = -1;
            "
          >
            ×
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
