// {{ .Project }}/tail-react/src/components/auth/PointCaptcha.tsx
import type { CaptchaPoint, PointCaptchaChallenge } from "@/api/auth";
import { useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";

interface Props {
  captcha: PointCaptchaChallenge;
  onRefresh: () => Promise<void>;
  onVerify: (points: CaptchaPoint[]) => Promise<{ verified: boolean }>;
  onChange: (points: CaptchaPoint[]) => void;
}

export default function PointCaptcha({ captcha, onRefresh, onVerify, onChange }: Props) {
  const { t } = useTranslation();
  const imageRef = useRef<HTMLImageElement>(null);
  const [points, setPoints] = useState<CaptchaPoint[]>([]);
  const [status, setStatus] = useState<"idle" | "pending" | "passed" | "error">("idle");

  useEffect(() => {
    setPoints([]);
    setStatus("idle");
    onChange([]);
  }, [captcha.captcha_id]); // eslint-disable-line react-hooks/exhaustive-deps

  const choose = async (event: React.MouseEvent<HTMLImageElement>) => {
    if (status === "pending" || status === "passed") return;
    const bounds = imageRef.current!.getBoundingClientRect();
    const point = {
      x: Math.round(((event.clientX - bounds.left) / bounds.width) * captcha.width),
      y: Math.round(((event.clientY - bounds.top) / bounds.height) * captcha.height),
    };
    const next = [...points, point].slice(0, captcha.target_count);
    setPoints(next);
    if (next.length !== captcha.target_count) return;
    setStatus("pending");
    try {
      const result = await onVerify(next);
      if (result.verified) {
        setStatus("passed");
        onChange(next);
      } else {
        setStatus("error");
        setPoints([]);
        onChange([]);
      }
    } catch {
      setStatus("error");
      setPoints([]);
      onChange([]);
    }
  };

  return (
    <div className="rounded-lg border border-gray-200 p-3 dark:border-gray-800">
      <div className="mb-2 flex items-center justify-between gap-3 text-xs text-gray-500 dark:text-gray-400">
        <span>{captcha.hint_text || t("auth.pointHint")}</span>
        <button type="button" className="font-medium text-brand-500" onClick={() => void onRefresh()}>{t("common.refresh")}</button>
      </div>
      <div className="relative overflow-hidden rounded-lg">
        <img ref={imageRef} alt={t("auth.pointCaptcha")} className="h-auto w-full cursor-crosshair" onClick={(event) => void choose(event)} src={captcha.captcha_image} />
        {points.map((point, index) => (
          <span key={`${point.x}-${point.y}-${index}`} className="absolute flex size-6 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full bg-brand-500 text-xs font-bold text-white shadow-theme-md" style={{ left: `${(point.x / captcha.width) * 100}%`, top: `${(point.y / captcha.height) * 100}%` }}>{index + 1}</span>
        ))}
      </div>
      <p className={`mt-2 text-xs ${status === "error" ? "text-error-500" : status === "passed" ? "text-success-500" : "text-gray-500"}`}>
        {status === "pending" ? t("common.verifying") : status === "passed" ? t("auth.pointPassed") : status === "error" ? t("auth.pointFailed") : t("auth.pointProgress", { count: captcha.target_count })}
      </p>
    </div>
  );
}

// {{ .Project }}/tdesign-vue3-mobile/src/components/PointCaptcha.vue
<script setup lang="ts">
import { nextTick, ref, watch } from 'vue';
import { request } from '../lib/api';
import type { PointCaptcha, CaptchaPoint } from '../lib/types';
import { t } from '../locales';
import { message, resolveMessage, type Feedback } from '../lib/form-feedback';
const props = defineProps<{ captcha: PointCaptcha; username?: string; authenticated?: boolean }>();
const emit = defineEmits<{ update: [value: PointCaptcha] }>();
const points = defineModel<CaptchaPoint[]>({ default: () => [] });
const selected = ref<CaptchaPoint[]>([]);
const image = ref<HTMLImageElement>();
const busy = ref(false);
const error = ref<Feedback>('');
const path = () => (props.authenticated ? '/auth/captcha' : '/auth/pub/captcha');
watch(
  () => props.captcha.captcha_id,
  () => {
    selected.value = [];
    points.value = [];
    error.value = '';
  },
);
async function refresh() {
  busy.value = true;
  error.value = '';
  points.value = [];
  selected.value = [];
  try {
    emit(
      'update',
      await request<PointCaptcha>(path(), {
        method: 'POST',
        public: !props.authenticated,
        body: { captcha_id: props.captcha.captcha_id },
      }),
    );
  } catch (e) {
    error.value = (e as Error).message;
  } finally {
    busy.value = false;
  }
}
async function select(event: MouseEvent) {
  if (busy.value || points.value.length || !image.value) return;
  const box = image.value.getBoundingClientRect();
  const p = {
    x: Math.round(((event.clientX - box.left) / box.width) * props.captcha.width),
    y: Math.round(((event.clientY - box.top) / box.height) * props.captcha.height),
  };
  const at = selected.value.findIndex((q) => (q.x - p.x) ** 2 + (q.y - p.y) ** 2 <= 196);
  if (at >= 0) {
    selected.value.splice(at, 1);
    return;
  }
  selected.value.push(p);
  if (selected.value.length < props.captcha.target_count) return;
  busy.value = true;
  error.value = '';
  try {
    const result = await request<{ verified: boolean; captcha?: PointCaptcha }>(
      `${path()}/verify`,
      {
        method: 'POST',
        public: !props.authenticated,
        body: {
          captcha_id: props.captcha.captcha_id,
          captcha_points: selected.value,
          ...(!props.authenticated ? { username: props.username } : {}),
        },
      },
    );
    if (result.verified) points.value = [...selected.value];
    else {
      selected.value = [];
      if (result.captcha) emit('update', result.captcha);
      await nextTick();
      error.value = message('app.captcha.failed');
    }
  } catch (e) {
    selected.value = [];
    error.value = (e as Error).message;
  } finally {
    busy.value = false;
  }
}
</script>
<template>
  <div class="point-captcha" :aria-busy="busy">
    <div class="section-heading">
      <span>{{ captcha.hint_text }}</span
      ><button type="button" :disabled="busy" @click="refresh">{{ t('refreshCaptcha') }}</button>
    </div>
    <div class="captcha-image" @click="select">
      <img ref="image" :src="captcha.captcha_image" :alt="t('captchaAlt')" /><span
        v-for="(p, index) in selected"
        :key="index"
        class="captcha-point"
        :style="{
          left: `${(p.x / captcha.width) * 100}%`,
          top: `${(p.y / captcha.height) * 100}%`,
        }"
        >{{ index + 1 }}</span
      >
    </div>
    <p v-if="error" role="alert" class="field-error">{{ resolveMessage(error) }}</p>
    <p v-if="points.length" class="success-text">{{ t('app.captcha.passed') }}</p>
  </div>
</template>
