// {{ .Project }}/ant-design-mobile/src/components/RemoteSelect.tsx
import { useEffect, useRef, useState } from 'react';
import { Button, SearchBar } from 'antd-mobile';
import { listResource, request } from '../lib/api';
import { loadOptionPage } from '../lib/option-pages';
import type { ResourceKind } from '../lib/types';
import { t } from '../locales';
import { Sheet, Icon, ErrorBox, NoData } from './UI';
import PageSkeleton from './PageSkeleton';
export interface Option {
  value: string | number;
  label: string;
}
export default function RemoteSelect({
  name,
  label,
  value,
  onChange,
  resource,
  multiple = false,
  group = false,
  msgRecipients = false,
  options,
  initial = [],
}: {
  name: string;
  label: string;
  value: unknown;
  onChange: (v: unknown) => void;
  resource?: ResourceKind;
  multiple?: boolean;
  group?: boolean;
  msgRecipients?: boolean;
  options?: Option[];
  initial?: Option[];
}) {
  const [open, setOpen] = useState(false),
    [query, setQuery] = useState(''),
    [loaded, setLoaded] = useState<Option[]>([]),
    [busy, setBusy] = useState(false),
    [error, setError] = useState(''),
    [retry, setRetry] = useState(0),
    [page, setPage] = useState(1),
    [hasMore, setHasMore] = useState(false);
  const labels = useRef(new Map<string | number, string>());
  initial.forEach((x) => labels.current.set(x.value, x.label));
  const selected = (
    Array.isArray(value)
      ? value
      : value !== undefined && value !== null && value !== ''
        ? [value]
        : []
  ) as (string | number)[];
  const choices = options || loaded;
  useEffect(() => {
    if (!open || options) return;
    let cancelled = false;
    const timer = setTimeout(
      async () => {
        setBusy(true);
        setError('');
        try {
          let data: Option[] = [];
          let more = false;
          if (msgRecipients) {
            const result = await request<{ id: number; username: string }[]>(
              `/msg/recipient-option?q=${encodeURIComponent(query)}`,
            );
            data = result.map((u) => ({ value: u.id, label: u.username }));
          } else if (group) {
            const result = await request<{ items: string[] }>(
              `/action/group?keyword=${encodeURIComponent(query)}`,
            );
            data = result.items.map((value) => ({ value, label: value }));
          } else if (resource) {
            const result = await loadOptionPage(resource, query, page, listResource);
            data = result.items;
            more = result.hasMore;
          }
          if (!cancelled) {
            setHasMore(more);
            setLoaded((previous) =>
              page === 1
                ? data
                : [...new Map([...previous, ...data].map((item) => [item.value, item])).values()],
            );
            data.forEach((x) => labels.current.set(x.value, x.label));
          }
        } catch (e) {
          if (!cancelled) setError((e as Error).message);
        } finally {
          if (!cancelled) setBusy(false);
        }
      },
      query ? 250 : 0,
    );
    return () => {
      cancelled = true;
      clearTimeout(timer);
    };
  }, [open, query, resource, group, options, retry, page, msgRecipients]);
  function choose(v: string | number) {
    onChange(
      multiple ? (selected.includes(v) ? selected.filter((x) => x !== v) : [...selected, v]) : v,
    );
    if (!multiple) setOpen(false);
  }
  const text = (v: string | number) =>
    labels.current.get(v) || choices.find((x) => x.value === v)?.label || String(v);
  return (
    <>
      <button
        id={name}
        type="button"
        className="select-trigger"
        aria-label={label}
        aria-expanded={open}
        onClick={() => {
          setQuery('');
          setPage(1);
          setLoaded([]);
          setHasMore(false);
          setBusy(!options);
          setError('');
          setOpen(true);
        }}
      >
        <span className={!selected.length ? 'muted' : ''}>
          {selected.map(text).join('、') || t('choose')}
        </span>
        <Icon name="chevron-down" size={18} />
      </button>
      <Sheet
        open={open}
        onClose={() => setOpen(false)}
        title={label}
        top={
          <>
            {(resource || group || msgRecipients) && (
              <SearchBar
                value={query}
                onChange={(value) => {
                  setQuery(value);
                  setPage(1);
                  setLoaded([]);
                  setHasMore(false);
                  setBusy(!options);
                }}
                placeholder={t('searchOptions')}
                aria-label={t('searchOptions')}
              />
            )}
            {multiple && (
              <p className="selection-count" role="status">
                {t('selected', { count: selected.length })}
              </p>
            )}
          </>
        }
        footer={
          <div className="sheet-actions">
            <Button onClick={() => onChange(multiple ? [] : undefined)}>{t('clear')}</Button>
            <Button color="primary" onClick={() => setOpen(false)}>
              {t('done')}
            </Button>
          </div>
        }
      >
        <div className="selected-options">
          {selected.map((v) => (
            <button
              className="resource-tag"
              type="button"
              key={v}
              onClick={() => onChange(multiple ? selected.filter((x) => x !== v) : undefined)}
            >
              {text(v)} <Icon name="close" size={12} />
            </button>
          ))}
        </div>
        <ErrorBox error={error} retry={() => setRetry((x) => x + 1)} />
        <div role="listbox" aria-label={label} aria-multiselectable={multiple}>
          {busy && !choices.length && <PageSkeleton variant="options" optionDetail={!!resource} />}
          {choices.map((item) => (
            <button
              key={item.value}
              type="button"
              className="option-row"
              role="option"
              aria-selected={selected.includes(item.value)}
              onClick={() => choose(item.value)}
            >
              <span className="option-copy">
                {item.label.includes(' · ') ? (
                  <>
                    <strong>{item.label.split(' · ')[0]}</strong>
                    <small> · {item.label.split(' · ').slice(1).join(' · ')}</small>
                  </>
                ) : (
                  item.label
                )}
              </span>
              <span className={`option-indicator ${multiple ? 'multiple' : ''}`} aria-hidden="true">
                {selected.includes(item.value) && <Icon name="check" size={18} />}
              </span>
            </button>
          ))}
          {group && query.trim() && !choices.some((x) => x.value === query.trim()) && (
            <button type="button" className="option-row" onClick={() => choose(query.trim())}>
              {t('createGroup', { name: query.trim() })}
            </button>
          )}
        </div>
        {!busy && !choices.length && !group && <NoData text={t('noResults')} />}
        {hasMore && (
          <Button block loading={busy} onClick={() => setPage((v) => v + 1)}>
            {t('loadMore')}
          </Button>
        )}
      </Sheet>
    </>
  );
}

// {{ .Project }}/tdesign-vue3-mobile/src/components/RemoteSelect.vue
<script setup lang="ts">
import { computed, ref, watch, onBeforeUnmount } from 'vue';
import { listResource, request } from '../lib/api';
import type { ResourceKind, RecordData } from '../lib/types';
import { t } from '../locales';
import Sheet from './Sheet.vue';
import PageSkeleton from './PageSkeleton.vue';
import Icon from './Icon.vue';
const props = defineProps<{
  name: string;
  label: string;
  resource?: ResourceKind;
  multiple?: boolean;
  msgRecipients?: boolean;
  group?: boolean;
  options?: { value: string | number; label: string }[];
  initial?: { value: string | number; label: string }[];
}>();
const model = defineModel<unknown>();
const open = ref(false);
const query = ref('');
const busy = ref(false);
const error = ref('');
const loaded = ref<{ value: string | number; label: string }[]>([]);
const labels = new Map<string | number, string>();
const selected = computed<(string | number)[]>(() =>
  Array.isArray(model.value)
    ? model.value
    : model.value !== '' && model.value !== undefined && model.value !== null
      ? [model.value as string | number]
      : [],
);
watch(
  () => props.initial,
  (value) => {
    for (const item of value || []) labels.set(item.value, item.label);
  },
  { immediate: true },
);
const options = computed(() => props.options || loaded.value);
const display = computed(() =>
  selected.value
    .map(
      (value) =>
        labels.get(value) || options.value.find((x) => x.value === value)?.label || String(value),
    )
    .join('、'),
);
const selectedLabels = computed(() =>
  selected.value.map((value) => ({
    value,
    label:
      labels.get(value) ||
      options.value.find((item) => item.value === value)?.label ||
      String(value),
  })),
);
let timer: ReturnType<typeof setTimeout> | undefined;
let generation = 0;
function option(record: RecordData) {
  const value = props.resource === 'action' ? String(record.code) : record.id;
  return { value, label: `${record.name || record.username} · ${record.word || record.code}` };
}
async function load() {
  const current = ++generation;
  if (props.options) return;
  busy.value = true;
  error.value = '';
  try {
    if (props.group) {
      const result = await request<{ items: string[] }>(
        `/action/group${query.value ? `?keyword=${encodeURIComponent(query.value)}` : ''}`,
      );
      if (current === generation)
        loaded.value = result.items.map((value) => ({ value, label: value }));
    } else if (props.msgRecipients) {
      const result = await request<{ id: number; username: string }[]>(
        `/msg/recipient-option?q=${encodeURIComponent(query.value)}`,
      );
      if (current === generation)
        loaded.value = result.map((user) => ({ value: user.id, label: user.username }));
    } else if (props.resource) {
      const q = query.value.trim();
      const fields = props.resource === 'user' ? ['username', 'code'] : ['name', 'word'];
      const results = await Promise.all(
        (q ? fields : ['']).map((field) =>
          listResource(props.resource!, { p: 1, s: 30, ...(field ? { [field]: q } : {}) }),
        ),
      );
      if (current === generation)
        loaded.value = [
          ...new Map(
            results
              .flatMap((result) => result.items)
              .map((record) => {
                const item = option(record);
                return [item.value, item];
              }),
          ).values(),
        ];
    }
    for (const item of loaded.value) labels.set(item.value, item.label);
  } catch (e) {
    if (current === generation) error.value = (e as Error).message;
  } finally {
    if (current === generation) busy.value = false;
  }
}
watch(query, () => {
  clearTimeout(timer);
  timer = setTimeout(load, 250);
});
watch(open, (value) => {
  if (value) {
    query.value = '';
    void load();
  }
});
onBeforeUnmount(() => {
  clearTimeout(timer);
  generation++;
});
function choose(value: string | number) {
  if (props.multiple)
    model.value = selected.value.includes(value)
      ? selected.value.filter((v) => v !== value)
      : [...selected.value, value];
  else {
    model.value = value;
    open.value = false;
  }
}
</script>
<template>
  <button
    :id="name"
    type="button"
    class="select-trigger"
    :aria-label="label"
    :aria-expanded="open"
    @click="open = true"
  >
    <span v-if="multiple && selected.length" class="selection-summary">
      <span v-for="item in selectedLabels.slice(0, 2)" :key="item.value" class="selection-chip">{{
        item.label
      }}</span>
      <span v-if="selected.length > 2" class="selection-count">{{
        t('moreSelected', { count: selected.length - 2 })
      }}</span>
    </span>
    <span v-else :class="{ muted: !display }">{{ display || t('choose') }}</span
    ><Icon name="chevron-down" :size="18" /></button
  ><Sheet v-model="open" :title="label"
    ><t-search
      v-if="!options?.length || resource || group"
      v-model="query"
      :placeholder="t('searchOptions')"
    />
    <p v-if="multiple" class="selection-count" role="status">
      {{ t('selected', { count: selected.length }) }}
    </p>
    <div v-if="display" class="selected-options">
      <t-tag
        v-for="value in selected"
        :key="value"
        closable
        @close="model = multiple ? selected.filter((x) => x !== value) : undefined"
        >{{ labels.get(value) || options.find((x) => x.value === value)?.label || value }}</t-tag
      >
    </div>
    <p v-if="error" class="form-error" role="alert">
      {{ error }}<button @click="load">{{ t('retry') }}</button>
    </p>
    <PageSkeleton v-if="busy" variant="options" />
    <div v-else role="listbox" :aria-label="label" :aria-multiselectable="multiple">
      <button
        v-for="item in options"
        :key="item.value"
        type="button"
        class="option-row"
        role="option"
        :aria-selected="selected.includes(item.value)"
        @click="choose(item.value)"
      >
        <span>{{ item.label }}</span
        ><Icon v-if="selected.includes(item.value)" name="check" :size="18" /></button
      ><button
        v-if="group && query.trim() && !options.some((x) => x.value === query.trim())"
        type="button"
        class="option-row"
        @click="choose(query.trim())"
      >
        {{ t('createGroup', { name: query.trim() }) }}
      </button>
    </div>
    <t-empty v-if="!busy && !options.length && !group" :description="t('noResults')" />
    <div class="sheet-actions">
      <t-button @click="model = multiple ? [] : undefined">{{ t('clear') }}</t-button
      ><t-button theme="primary" @click="open = false">{{ t('done') }}</t-button>
    </div></Sheet
  >
</template>
