// {{ .Project }}/ant-design-mobile/src/pages/MsgPage.tsx
import { useState, useRef, useEffect } from "react";
import { Link, useLocation } from "react-router-dom";
import { Button, Tag, Checkbox } from "antd-mobile";
import { session } from "../lib/api";
import { useMessages } from "../lib/use-messages";
import { dateTime, parseDateTime } from "../lib/format";
import { t } from "../locales";
import {
  Icon,
  Sheet,
  Field,
  TextField,
  ErrorBox,
  NoData,
} from "../components/UI";
import RemoteSelect from "../components/RemoteSelect";
import DateTimeField from "../components/DateTimeField";
import PageSkeleton from "../components/PageSkeleton";
import ResultToolbar from "../components/ResultToolbar";
import RecordPagination from "../components/RecordPagination";
import ResultOptions from "../components/ResultOptions";
const tr = (key: string) => t(`app.msg.${key}`);
export default function MsgPage() {
  const composeForm = useRef<HTMLFormElement>(null);
  const sent = useLocation().pathname === "/system/msg";
  const permitted = (action: string) =>
    session.user?.permission.btns.some(
      (code) => code === "*" || code === `system.msg.${action}`,
    ) ?? false;
  const readable = !sent || permitted("read"),
    deletable = !sent || permitted("delete");
  const m = useMessages(sent, readable, tr, (value) =>
    parseDateTime(value).valueOf(),
  );
  const [selecting, setSelecting] = useState(false);
  const [checkedIDs, setCheckedIDs] = useState<number[]>([]);
  const checkedVisible = checkedIDs.filter((id) =>
    m.rows.some((row) => row.id === id),
  );
  useEffect(() => {
    setCheckedIDs([]);
  }, [sent, m.page, m.size, m.type, m.status]);
  const [options, setOptions] = useState(""),
    [density, setDensity] = useState("default"),
    [columns, setColumns] = useState([
      "title",
      "type",
      "scope",
      "published_at",
    ]);
  const [bordered, setBordered] = useState(false),
    [striped, setStriped] = useState(false),
    [sticky, setSticky] = useState(true);
  async function send() {
    await m.send();
    if (Object.values(m.issues).some(Boolean))
      requestAnimationFrame(() => {
        const field = composeForm.current?.querySelector<HTMLElement>(
          ".field.invalid input,.field.invalid textarea,.field.invalid button",
        );
        field?.scrollIntoView({ block: "center" });
        field?.focus();
      });
  }
  const fields = ["title", "type", "scope", "published_at"].map((key) => ({
    key,
    title: tr(key === "published_at" ? "published" : key),
  }));
  return (
    <section
      className={`page management density-${density} ${bordered ? "bordered" : ""} ${striped ? "striped" : ""} ${sticky ? "sticky-toolbar" : ""}`}
      data-testid="message-management-page"
      aria-busy={m.loading}
    >
      <header className="page-heading">
        <Link
          to={sent ? "/dashboard/overview?tab=manage" : "/dashboard/overview"}
          className="back-link"
          aria-label={t(sent ? "manage" : "home")}
        >
          <Icon name="chevron-left" />
        </Link>
        <div>
          <h1>{tr(sent ? "manage" : "inbox")}</h1>
        </div>
      </header>
      <section className="search-region">
        <Field name="msg-filter-type" label={tr("type")}>
          <RemoteSelect
            name="msg-filter-type"
            label={tr("type")}
            value={m.type}
            onChange={(v) => m.setType(String(v ?? ""))}
            options={["", "system", "notice"].map((value) => ({
              value,
              label: tr(value || "allTypes"),
            }))}
          />
        </Field>
        {!sent && (
          <div className="segmented" role="group" aria-label={tr("read")}>
            {["", "unread", "read"].map((value) => (
              <button
                key={value}
                aria-pressed={m.status === value}
                className={m.status === value ? "active" : ""}
                onClick={() => m.setStatus(value)}
              >
                {tr(value || "allStatus")}
              </button>
            ))}
          </div>
        )}
        <div className="search-actions message-search-actions">
          <button
            className="search-reset"
            onClick={() => {
              m.setType("");
              m.setStatus("");
            }}
          >
            <Icon name="refresh" size={14} />
            <span>{t("system.common.reset")}</span>
          </button>
          <button className="search-submit" onClick={() => void m.load()}>
            <Icon name="search" size={14} />
            <span>{t("system.common.search")}</span>
          </button>
        </div>
      </section>
      <div className="results-region">
        <ResultToolbar
          disabled={!readable}
          refresh={() => void m.load()}
          options={setOptions}
        >
          {sent && permitted("send") && (
            <Button
              className="create-record"
              size="small"
              color="primary"
              onClick={m.newMessage}
            >
              <Icon name="add" size={16} />
              <span className="create-label">{tr("send")}</span>
            </Button>
          )}
          {!sent && (
            <Button
              size="small"
              disabled={m.loading || m.busy}
              onClick={() => void m.readAll()}
            >
              {tr("readAll")}
            </Button>
          )}{" "}
        </ResultToolbar>
        <div className="selection-tools">
          <div className="selection-actions">
            {readable && m.rows.length > 0 && (deletable || !sent) && (
              <button
                className="action-chip action-chip-quiet"
                disabled={m.busy || m.loading}
                onClick={() => {
                  setSelecting((v) => !v);
                  setCheckedIDs([]);
                }}
              >
                <Icon
                  name={selecting ? "check" : "check-rectangle"}
                  size={16}
                />
                <span>{t(selecting ? "done" : "select")}</span>
              </button>
            )}
            {selecting && (
              <button
                className="action-chip action-chip-quiet"
                disabled={m.busy || m.loading}
                onClick={() =>
                  setCheckedIDs(
                    checkedVisible.length === m.rows.length
                      ? []
                      : m.rows.map((row) => row.id),
                  )
                }
              >
                <Icon name="check-double" size={16} />
                <span>{t("system.common.selectAll")}</span>
              </button>
            )}

            {checkedVisible.length > 0 && deletable && (
              <button
                data-testid="message-bulk-delete"
                className="action-chip action-chip-danger"
                disabled={m.busy || m.loading}
                onClick={() => m.requestBulk(checkedVisible, "deleteSelected")}
              >
                <Icon name="delete" size={16} />
                <span>{tr("deleteSelected")}</span>
              </button>
            )}
            {checkedVisible.length > 0 && !sent && (
              <button
                data-testid="message-bulk-read"
                className="action-chip action-chip-quiet"
                disabled={m.busy || m.loading}
                onClick={() => m.requestBulk(checkedVisible, "readSelected")}
              >
                <Icon name="check" size={16} />
                <span>{tr("markRead")}</span>
              </button>
            )}
          </div>
          <span className="result-count">
            {t("system.table.total", { count: m.total })}
          </span>
        </div>
        {!readable ? (
          <NoData text={tr("noPermission")} />
        ) : (
          <>
            <ErrorBox error={m.error} retry={() => void m.load()} />
            {m.loading ? (
              <PageSkeleton variant="list" />
            ) : (
              <div className="card record-list">
                {m.rows.map((row) => (
                  <article
                    className="record-item"
                    key={row.id}
                    data-record-id={row.id}
                  >
                    <div className="record">
                      {selecting && (
                        <Checkbox
                          aria-label={`${t("select")} ${row.title}`}
                          disabled={m.busy || m.loading}
                          checked={checkedVisible.includes(row.id)}
                          onChange={(checked) =>
                            setCheckedIDs((ids) =>
                              checked
                                ? [...ids, row.id]
                                : ids.filter((id) => id !== row.id),
                            )
                          }
                        />
                      )}
                      <button
                        className="record-open"
                        aria-label={`${tr("view")} ${row.title}`}
                        onClick={() => void m.openDetail(row)}
                      >
                        <span className="record-kind">
                          <Icon name="notification" />
                        </span>
                        <span className="record-main">
                          <strong>{row.title}</strong>
                          <span className="record-summary">
                            {columns.includes("type") && (
                              <Tag color="primary" fill="outline">
                                {tr(row.type)}
                              </Tag>
                            )}
                            {columns.includes("scope") && (
                              <Tag fill="outline">{tr(row.scope)}</Tag>
                            )}
                            {row.expired_at && row.expired_at <= Date.now() && (
                              <Tag>{tr("expired")}</Tag>
                            )}
                          </span>
                        </span>
                        {!sent && (
                          <Tag color={row.read_at ? "default" : "primary"}>
                            {tr(row.read_at ? "read" : "unread")}
                          </Tag>
                        )}
                        <Icon name="chevron-right" size={16} />
                      </button>
                    </div>
                    {columns.includes("published_at") && (
                      <dl className="record-fields">
                        <div>
                          <dt>{tr("published")}</dt>
                          <dd>{dateTime(row.published_at)}</dd>
                        </div>
                      </dl>
                    )}
                    {!sent && !row.read_at && (
                      <div className="selection-actions">
                        <button
                          className="action-chip action-chip-quiet"
                          disabled={m.busy}
                          onClick={() => void m.mark(row)}
                        >
                          {tr("markRead")}
                        </button>
                      </div>
                    )}
                  </article>
                ))}
                {!m.rows.length && <NoData text={tr("empty")} />}
              </div>
            )}
            <RecordPagination
              page={m.page}
              size={m.size}
              total={m.total}
              loading={m.loading}
              change={m.setPage}
              options={() => setOptions("pageSize")}
            />
          </>
        )}
      </div>
      <ResultOptions
        options={options}
        setOptions={setOptions}
        density={density}
        setDensity={setDensity}
        size={m.size}
        setSize={m.setSize}
        setPage={m.setPage}
        columns={columns}
        setColumns={setColumns}
        fields={fields}
        identity="title"
        bordered={bordered}
        setBordered={setBordered}
        striped={striped}
        setStriped={setStriped}
        sticky={sticky}
        setSticky={setSticky}
      />
      <Sheet
        open={m.detail}
        onClose={m.closeDetail}
        title={tr("detail")}
        footer={
          m.selected && deletable ? (
            <Button
              color="danger"
              fill="outline"
              onClick={() => m.remove(m.selected!)}
            >
              {tr(sent ? "deleteGlobal" : "delete")}
            </Button>
          ) : undefined
        }
      >
        {m.detailLoading ? (
          <PageSkeleton />
        ) : (
          m.selected && (
            <>
              <div className="detail-identity">
                <span className="avatar large">
                  <Icon name="notification" />
                </span>
                <h2>{m.selected.title}</h2>
              </div>
              <dl className="details">
                {[
                  ["type", tr(m.selected.type)],
                  ["scope", tr(m.selected.scope)],
                  ["published", dateTime(m.selected.published_at)],
                  ["content", m.selected.content],
                  [
                    "expiry",
                    m.selected.expired_at
                      ? dateTime(m.selected.expired_at)
                      : tr("noExpiry"),
                  ],
                  ...(sent && m.selected.recipient_ids
                    ? [["recipientIDs", m.selected.recipient_ids.join(", ")]]
                    : []),
                ].map(([key, value]) => (
                  <div
                    key={key}
                    className={key === "content" ? "detail-wide" : ""}
                  >
                    <dt>{tr(key)}</dt>
                    <dd className="msg-content">{value}</dd>
                  </div>
                ))}
              </dl>
            </>
          )
        )}
      </Sheet>
      <Sheet
        open={!!m.confirmation}
        onClose={() => m.setConfirmation("")}
        busy={m.busy}
        title={tr("confirm")}
        footer={
          <div className="sheet-actions">
            <Button disabled={m.busy} onClick={() => m.setConfirmation("")}>
              {tr("cancel")}
            </Button>
            <Button
              loading={m.busy}
              color={
                m.confirmation === "delete" ||
                m.confirmation === "deleteSelected"
                  ? "danger"
                  : "primary"
              }
              onClick={async () => {
                if (await m.confirm()) setCheckedIDs([]);
              }}
            >
              {tr("confirm")}
            </Button>
          </div>
        }
      >
        <p>
          {tr(
            m.confirmation === "readSelected"
              ? "readSelectedConfirm"
              : m.confirmation === "deleteSelected"
                ? sent
                  ? "deleteSelectedGlobalConfirm"
                  : "deleteSelectedConfirm"
                : sent
                  ? "deleteGlobalConfirm"
                  : "deleteConfirm",
          )}
        </p>
        <ErrorBox error={m.error} />
      </Sheet>
      <Sheet
        open={m.compose}
        onClose={() => m.setCompose(false)}
        dirty={m.dirty}
        busy={m.busy}
        title={tr("send")}
        footer={(close) => (
          <div className="sheet-actions">
            <Button disabled={m.busy} onClick={close}>
              {tr("cancel")}
            </Button>
            <Button
              color="primary"
              loading={m.busy}
              onClick={() => void send()}
            >
              {tr("send")}
            </Button>
          </div>
        )}
      >
        <form
          ref={composeForm}
          noValidate
          onSubmit={(e) => {
            e.preventDefault();
            void send();
          }}
        >
          <fieldset disabled={m.busy}>
            <TextField
              name="msg-title"
              label={tr("title")}
              required
              value={m.draft.title}
              onChange={(title) => m.setDraft((d) => ({ ...d, title }))}
              error={m.attempted ? m.issues.title : ""}
            />
            <TextField
              name="msg-content"
              label={tr("content")}
              required
              multiline
              value={m.draft.content}
              onChange={(content) => m.setDraft((d) => ({ ...d, content }))}
              error={m.attempted ? m.issues.content : ""}
            />
            <Field name="msg-type" label={tr("type")}>
              <RemoteSelect
                name="msg-type"
                label={tr("type")}
                value={m.draft.type}
                onChange={(value) =>
                  m.setDraft((d) => ({
                    ...d,
                    type: value as "notice" | "system",
                  }))
                }
                options={["system", "notice"].map((value) => ({
                  value,
                  label: tr(value),
                }))}
              />
            </Field>
            <Field name="msg-scope" label={tr("scope")}>
              <RemoteSelect
                name="msg-scope"
                label={tr("scope")}
                value={m.draft.scope}
                onChange={(value) =>
                  m.setDraft((d) => ({
                    ...d,
                    scope: value as "all" | "targeted",
                  }))
                }
                options={["all", "targeted"].map((value) => ({
                  value,
                  label: tr(value),
                }))}
              />
            </Field>
            {m.draft.scope === "targeted" && (
              <Field
                name="msg-recipients"
                label={tr("recipients")}
                required
                error={m.attempted ? m.issues.recipients : ""}
              >
                <RemoteSelect
                  name="msg-recipients"
                  label={tr("recipients")}
                  value={m.draft.recipient_ids}
                  onChange={(value) =>
                    m.setDraft((d) => ({
                      ...d,
                      recipient_ids: value as number[],
                    }))
                  }
                  msgRecipients
                  multiple
                />
              </Field>
            )}
            <Field
              name="msg-expiry"
              label={tr("expiry")}
              error={m.attempted ? m.issues.expiry : ""}
            >
              <DateTimeField
                id="msg-expiry"
                name="msg-expiry"
                value={m.expiry}
                onChange={m.setExpiry}
              />
            </Field>
            <ErrorBox error={m.sendError} />
          </fieldset>
        </form>
      </Sheet>
    </section>
  );
}

// {{ .Project }}/tdesign-vue3-mobile/src/pages/MsgPage.vue
<script setup lang="ts">
import type { Msg, MsgInput } from "../lib/msg";
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { useRoute } from "vue-router";
import { session } from "../lib/api";
import { msgApi, msgChanged } from "../lib/msg";
import { dateTime, parseDateTime } from "../lib/format";
import { useUnsavedForm } from "../lib/unsaved-form";
import { t } from "../locales";
import Sheet from "../components/Sheet.vue";
import Icon from "../components/Icon.vue";
import EditorForm from "../components/EditorForm.vue";
import RecordPagination from "../components/RecordPagination.vue";
import ResultToolbar from "../components/ResultToolbar.vue";
import ResultOptions from "../components/ResultOptions.vue";
import Field from "../components/Field.vue";
import RemoteSelect from "../components/RemoteSelect.vue";
import DateTimeField from "../components/DateTimeField.vue";
import DiscardSheet from "../components/DiscardSheet.vue";
import PageSkeleton from "../components/PageSkeleton.vue";
const route = useRoute();
const tr = (key: string, params?: Record<string, string | number>) =>
  t(`app.msg.${key}`, params);
const sent = computed(() => route.path === "/system/msg");
const permitted = (action: string) =>
  session.user?.permission.btns.some(
    (code: string) => code === "*" || code === `system.msg.${action}`,
  ) ?? false;
const canRead = computed(() => !sent.value || permitted("read"));
const canSend = computed(() => sent.value && permitted("send"));
const canDelete = computed(() => !sent.value || permitted("delete"));
const rows = ref<Msg[]>([]),
  total = ref(0),
  page = ref(1),
  size = ref(20);
const loading = ref(false),
  error = ref(""),
  busy = ref(false),
  status = ref(""),
  type = ref("");
const selected = ref<Msg>(),
  detailOpen = ref(false),
  detailLoading = ref(false);
const compose = ref(false),
  attempted = ref(false),
  sendError = ref(""),
  expiry = ref("");
const form = ref<MsgInput>({
  title: "",
  content: "",
  type: "notice",
  scope: "all",
  recipient_ids: [],
  expired_at: null,
});
const density = ref("default");
const bordered = ref(false),
  striped = ref(false),
  sticky = ref(true);
const visible = ref(["type", "scope", "published_at"]);
const columns = computed(() =>
  ["title", "type", "scope", "published_at"].map((key) => ({
    key,
    title: tr(key === "published_at" ? "published" : key),
  })),
);
const composeForm = ref<InstanceType<typeof EditorForm>>();
const composeSheet = ref<InstanceType<typeof Sheet>>();
const settings = ref("");
const selecting = ref(false);
const checkedIDs = ref<number[]>([]);
const checkedVisible = computed(() =>
  checkedIDs.value.filter((id) => rows.value.some((row) => row.id === id)),
);
const pendingIDs = ref<number[]>([]);
function requestBulk(read = false) {
  if (
    busy.value ||
    !checkedVisible.value.length ||
    (read ? sent.value : !canDelete.value)
  )
    return;
  pendingIDs.value = [...checkedVisible.value];
  confirmation.value = read ? "readSelected" : "deleteSelected";
}
const confirmation = ref<"delete" | "deleteSelected" | "readSelected" | "">("");
const confirmOpen = computed({
  get: () => !!confirmation.value,
  set: (v: boolean) => {
    if (!v) confirmation.value = "";
  },
});
let generation = 0,
  detailGeneration = 0,
  sendKey = "",
  lastPayload = "",
  initialDraft = "";
const dirty = () =>
  compose.value &&
  (JSON.stringify(form.value) !== initialDraft || !!expiry.value);
const { discardOpen, decide, beforeClose } = useUnsavedForm(
  dirty,
  () => busy.value,
);
const issues = computed(() => ({
  title:
    !form.value.title.trim() || [...form.value.title.trim()].length > 200
      ? tr("titleError")
      : "",
  content:
    !form.value.content.trim() || [...form.value.content.trim()].length > 20000
      ? tr("contentError")
      : "",
  recipients:
    form.value.scope === "targeted" &&
    (!form.value.recipient_ids?.length ||
      form.value.recipient_ids.length > 1000)
      ? tr("recipientError")
      : "",
  expiry:
    expiry.value &&
    (!parseDateTime(expiry.value).isValid() ||
      parseDateTime(expiry.value).valueOf() <= Date.now())
      ? tr("expiryError")
      : "",
}));
async function load() {
  const current = ++generation;
  if (!canRead.value) {
    rows.value = [];
    total.value = 0;
    return;
  }
  loading.value = true;
  error.value = "";
  try {
    const result = await msgApi.list(sent.value, {
      p: page.value,
      s: size.value,
      ...(type.value ? { type: type.value } : {}),
      ...(!sent.value && status.value ? { read: status.value === "read" } : {}),
    });
    if (current !== generation) return;
    if (
      !result.items.length &&
      page.value > 1 &&
      result.t <= (page.value - 1) * size.value
    ) {
      page.value--;
      return;
    }
    rows.value = result.items;
    total.value = result.t;
  } catch (e) {
    if (current === generation) {
      error.value = (e as Error).message;
      rows.value = [];
    }
  } finally {
    if (current === generation) loading.value = false;
  }
}
async function openDetail(row: Msg) {
  const current = ++detailGeneration;
  detailOpen.value = true;
  selected.value = undefined;
  detailLoading.value = true;
  error.value = "";
  try {
    const result = await msgApi.get(row.id, sent.value);
    if (current !== detailGeneration || !detailOpen.value) return;
    selected.value = result;
    if (!sent.value && !result.read_at) {
      await msgApi.read(result.id);
      result.read_at = Date.now();
      msgChanged();
      await load();
    }
  } catch (e) {
    error.value = (e as Error).message;
    detailOpen.value = false;
  } finally {
    if (current === detailGeneration) detailLoading.value = false;
  }
}
async function mark(row: Msg) {
  busy.value = true;
  try {
    await msgApi.read(row.id);
    msgChanged();
    await load();
  } catch (e) {
    error.value = (e as Error).message;
  } finally {
    busy.value = false;
  }
}
async function readAll() {
  if (busy.value || sent.value) return;
  busy.value = true;
  error.value = "";
  try {
    await msgApi.readAll();
  } catch (e) {
    error.value = (e as Error).message;
  } finally {
    msgChanged();
    await load();
    busy.value = false;
  }
}
async function confirm() {
  if (busy.value) return;
  busy.value = true;
  error.value = "";
  try {
    if (
      confirmation.value === "deleteSelected" ||
      confirmation.value === "readSelected"
    ) {
      for (const id of [...pendingIDs.value]) {
        if (confirmation.value === "readSelected") await msgApi.read(id);
        else await msgApi.remove(id, sent.value);
        pendingIDs.value = pendingIDs.value.filter((value) => value !== id);
        checkedIDs.value = checkedIDs.value.filter((value) => value !== id);
      }
    } else if (selected.value)
      await msgApi.remove(selected.value.id, sent.value);
    checkedIDs.value = [];
    confirmation.value = "";
    detailOpen.value = false;
  } catch (e) {
    error.value = (e as Error).message;
  } finally {
    msgChanged();
    await load();
    busy.value = false;
  }
}
function newMessage() {
  form.value = {
    title: "",
    content: "",
    type: "notice",
    scope: "all",
    recipient_ids: [],
    expired_at: null,
  };
  expiry.value = "";
  attempted.value = false;
  sendError.value = "";
  sendKey = crypto.randomUUID();
  lastPayload = "";
  initialDraft = JSON.stringify(form.value);
  compose.value = true;
}
async function send() {
  if (busy.value) return;
  attempted.value = true;
  if (Object.values(issues.value).some(Boolean)) {
    await composeForm.value?.focusInvalid();
    return;
  }
  busy.value = true;
  sendError.value = "";
  try {
    const payload = {
      ...form.value,
      recipient_ids:
        form.value.scope === "targeted" ? form.value.recipient_ids : [],
      expired_at: expiry.value ? parseDateTime(expiry.value).valueOf() : null,
    };
    const serialized = JSON.stringify(payload);
    if (serialized !== lastPayload) {
      sendKey = crypto.randomUUID();
      lastPayload = serialized;
    }
    await msgApi.send(payload, sendKey);
    compose.value = false;
    msgChanged();
    if (page.value !== 1) page.value = 1;
    else await load();
  } catch (e) {
    sendError.value = (e as Error).message;
  } finally {
    busy.value = false;
  }
}
watch([sent, status, type, size], () => {
  page.value = 1;
  detailOpen.value = false;
  void load();
});
watch(sent, () => {
  confirmation.value = "";
});
watch([sent, page, size, status, type], () => {
  checkedIDs.value = [];
});
watch(page, load);
watch(canRead, load, { immediate: true });
function refreshVisible() {
  if (!document.hidden && !busy.value && !loading.value && canRead.value)
    void load();
}
let refreshTimer: ReturnType<typeof setInterval>;
onMounted(() => {
  refreshTimer = setInterval(refreshVisible, 30000);
  window.addEventListener("cinch-msg-changed", refreshVisible);
  document.addEventListener("visibilitychange", refreshVisible);
});
onBeforeUnmount(() => {
  clearInterval(refreshTimer);
  window.removeEventListener("cinch-msg-changed", refreshVisible);
  document.removeEventListener("visibilitychange", refreshVisible);
  generation++;
  detailGeneration++;
});
</script>
<template>
  <section
    class="page management"
    data-testid="message-management-page"
    :class="[
      `density-${density}`,
      { bordered, striped, 'sticky-toolbar': sticky },
    ]"
    :aria-busy="loading"
  >
    <header class="page-heading">
      <RouterLink
        :to="sent ? '/dashboard/overview?tab=manage' : '/dashboard/overview'"
        class="back-link"
        :aria-label="t(sent ? 'manage' : 'home')"
        ><Icon name="chevron-left" :size="22"
      /></RouterLink>
      <div>
        <h1>{{ tr(sent ? "manage" : "inbox") }}</h1>
      </div>
    </header>
    <section class="search-region">
      <Field name="msg-filter-type" :label="tr('type')"
        ><RemoteSelect
          v-model="type"
          name="msg-filter-type"
          :label="tr('type')"
          :options="[
            { value: '', label: tr('allTypes') },
            { value: 'system', label: tr('system') },
            { value: 'notice', label: tr('notice') },
          ]"
      /></Field>
      <div
        v-if="!sent"
        class="segmented msg-status-filter"
        role="group"
        :aria-label="tr('read')"
      >
        <button
          v-for="value in ['', 'unread', 'read']"
          :key="value"
          :class="{ active: status === value }"
          :aria-pressed="status === value"
          @click="status = value"
        >
          {{ tr(value || "allStatus") }}
        </button>
      </div>
      <div class="search-actions message-search-actions">
        <button
          class="action-chip action-chip-quiet"
          @click="
            type = '';
            status = '';
          "
        >
          <span>{{ t("system.common.reset") }}</span></button
        ><button class="action-chip action-chip-primary" @click="load">
          <span>{{ t("system.common.search") }}</span>
        </button>
      </div>
    </section>
    <div class="results-region">
      <ResultToolbar
        :can-read="canRead"
        @refresh="load"
        @options="settings = $event"
      >
        <button
          v-if="canSend"
          class="create-button create-labeled"
          @click="newMessage"
        >
          <Icon name="add" :size="20" /><span>{{ tr("send") }}</span>
        </button>
        <button
          v-if="!sent"
          class="action-chip action-chip-quiet"
          :disabled="loading || busy"
          @click="readAll"
        >
          <Icon name="check-double" :size="16" /><span>{{
            tr("readAll")
          }}</span>
        </button>
      </ResultToolbar>
      <div class="selection-tools">
        <div class="selection-actions">
          <button
            v-if="canRead && rows.length && (canDelete || !sent)"
            class="action-chip action-chip-quiet"
            :disabled="busy || loading"
            @click="
              selecting = !selecting;
              checkedIDs = [];
            "
          >
            <Icon
              :name="selecting ? 'check' : 'check-rectangle'"
              :size="16"
            /><span>{{ t(selecting ? "done" : "select") }}</span>
          </button>
          <button
            v-if="selecting"
            class="action-chip action-chip-quiet"
            :disabled="busy || loading"
            @click="
              checkedIDs =
                checkedVisible.length === rows.length
                  ? []
                  : rows.map((row) => row.id)
            "
          >
            <Icon name="check-double" :size="16" /><span>{{
              t("system.common.selectAll")
            }}</span>
          </button>

          <button
            data-testid="message-bulk-delete"
            v-if="checkedVisible.length && canDelete"
            class="action-chip action-chip-danger"
            :disabled="busy || loading"
            @click="requestBulk()"
          >
            <Icon name="delete" :size="16" /><span>{{
              tr("deleteSelected")
            }}</span>
          </button>
          <button
            data-testid="message-bulk-read"
            v-if="checkedVisible.length && !sent"
            class="action-chip action-chip-quiet"
            :disabled="busy || loading"
            @click="requestBulk(true)"
          >
            <Icon name="check" :size="16" /><span>{{ tr("markRead") }}</span>
          </button>
        </div>
        <span class="result-count">{{
          t("system.table.total", { count: total })
        }}</span>
      </div>
      <p v-if="!canRead" class="field-hint">{{ tr("noPermission") }}</p>
      <div v-else-if="error" class="form-error" role="alert">
        <p>{{ error }}</p>
        <button @click="load">{{ tr("retry") }}</button>
      </div>
      <PageSkeleton v-else-if="loading" variant="list" />
      <div v-else class="card record-list">
        <article
          v-for="row in rows"
          :key="row.id"
          class="record-wrap"
          :data-record-id="row.id"
        >
          <div class="record">
            <t-checkbox
              v-if="selecting"
              :checked="checkedVisible.includes(row.id)"
              :disabled="busy || loading"
              :aria-label="`${t('select')} ${row.title}`"
              @change="
                checkedIDs = checkedVisible.includes(row.id)
                  ? checkedIDs.filter((id) => id !== row.id)
                  : [...checkedIDs, row.id]
              "
            />
            <button
              class="record-open"
              :aria-label="`${tr('view')} ${row.title}`"
              @click="openDetail(row)"
            >
              <span class="avatar"><Icon name="notification" /></span>
              <div class="record-main">
                <strong>{{ row.title }}</strong>
                <div class="record-summary">
                  <t-tag
                    v-if="visible.includes('type')"
                    theme="primary"
                    variant="light"
                    >{{ tr(row.type) }}</t-tag
                  ><t-tag v-if="visible.includes('scope')" variant="light">{{
                    tr(row.scope)
                  }}</t-tag
                  ><t-tag
                    v-if="row.expired_at && row.expired_at <= Date.now()"
                    >{{ tr("expired") }}</t-tag
                  >
                </div>
              </div>
              <t-tag
                v-if="!sent"
                :theme="row.read_at ? 'default' : 'primary'"
                >{{ tr(row.read_at ? "read" : "unread") }}</t-tag
              ><Icon name="chevron-right" :size="16" />
            </button>
          </div>
          <div v-if="visible.includes('published_at')" class="record-extra">
            <span>{{ tr("published") }}</span
            ><span>{{ dateTime(row.published_at) }}</span>
          </div>
          <div
            v-if="!sent && !row.read_at"
            class="selection-actions msg-read-action"
          >
            <button
              class="action-chip action-chip-quiet"
              :disabled="busy"
              @click="mark(row)"
            >
              <Icon name="check" :size="16" /><span>{{ tr("markRead") }}</span>
            </button>
          </div>
        </article>
        <t-empty v-if="!rows.length" :description="tr('empty')" />
      </div>
      <RecordPagination
        v-if="canRead"
        :page="page"
        :size="size"
        :total="total"
        :loading="loading"
        @previous="page--"
        @next="page++"
        @page-size="settings = 'pageSize'"
      />
    </div>
    <ResultOptions
      v-model:option="settings"
      v-model:density="density"
      v-model:size="size"
      v-model:visible="visible"
      v-model:bordered="bordered"
      v-model:striped="striped"
      v-model:sticky="sticky"
      :columns="columns"
      fixed-column="title"
    />
    <Sheet v-model="detailOpen" :title="tr('detail')"
      ><PageSkeleton v-if="detailLoading" /><template v-else-if="selected"
        ><div class="detail-identity">
          <span class="avatar large"
            ><Icon name="notification" :size="30"
          /></span>
          <h2>{{ selected.title }}</h2>
        </div>
        <dl class="details">
          <dt>{{ tr("type") }}</dt>
          <dd>
            <t-tag theme="primary" variant="light">{{
              tr(selected.type)
            }}</t-tag>
          </dd>
          <dt>{{ tr("scope") }}</dt>
          <dd>{{ tr(selected.scope) }}</dd>
          <dt>{{ tr("published") }}</dt>
          <dd>{{ dateTime(selected.published_at) }}</dd>
          <dt>{{ tr("content") }}</dt>
          <dd class="msg-content">{{ selected.content }}</dd>
          <dt>{{ tr("expiry") }}</dt>
          <dd>
            {{
              selected.expired_at
                ? dateTime(selected.expired_at)
                : tr("noExpiry")
            }}
          </dd>
        </dl>
        <p v-if="sent && selected.recipient_ids" class="msg-content">
          {{ tr("recipientIDs") }}: {{ selected.recipient_ids.join(", ") }}
        </p>
        <div class="detail-actions">
          <t-button
            v-if="canDelete"
            theme="danger"
            variant="outline"
            @click="confirmation = 'delete'"
            >{{ tr(sent ? "deleteGlobal" : "delete") }}</t-button
          >
        </div></template
      ></Sheet
    >
    <Sheet
      v-model="confirmOpen"
      :title="tr('confirm')"
      :before-close="() => !busy"
      ><p>
        {{
          tr(
            confirmation === "readSelected"
              ? "readSelectedConfirm"
              : confirmation === "deleteSelected"
                ? sent
                  ? "deleteSelectedGlobalConfirm"
                  : "deleteSelectedConfirm"
                : sent
                  ? "deleteGlobalConfirm"
                  : "deleteConfirm",
          )
        }}
      </p>
      <p v-if="error" role="alert">{{ error }}</p>
      <div class="sheet-actions">
        <t-button :disabled="busy" @click="confirmation = ''">{{
          tr("cancel")
        }}</t-button
        ><t-button
          :theme="
            confirmation === 'delete' || confirmation === 'deleteSelected'
              ? 'danger'
              : 'primary'
          "
          :loading="busy"
          @click="confirm"
          >{{ tr("confirm") }}</t-button
        >
      </div></Sheet
    >
    <Sheet
      ref="composeSheet"
      v-model="compose"
      :title="tr('send')"
      :before-close="beforeClose"
    >
      <EditorForm ref="composeForm" :busy="busy" @submit="send">
        <Field
          name="msg-title"
          :label="tr('title')"
          required
          :error="attempted ? issues.title : ''"
          ><t-input
            v-model="form.title"
            name="msg-title"
            :placeholder="t('system.common.enter', { field: tr('title') })"
        /></Field>
        <Field
          name="msg-content"
          :label="tr('content')"
          required
          :error="attempted ? issues.content : ''"
          ><t-textarea
            v-model="form.content"
            name="msg-content"
            :placeholder="t('system.common.enter', { field: tr('content') })"
            :autosize="{ minRows: 3, maxRows: 9 }"
        /></Field>
        <Field name="msg-type" :label="tr('type')"
          ><RemoteSelect
            v-model="form.type"
            name="msg-type"
            :label="tr('type')"
            :options="
              ['system', 'notice'].map((value) => ({ value, label: tr(value) }))
            "
        /></Field>
        <Field name="msg-scope" :label="tr('scope')"
          ><RemoteSelect
            v-model="form.scope"
            name="msg-scope"
            :label="tr('scope')"
            :options="
              ['all', 'targeted'].map((value) => ({ value, label: tr(value) }))
            "
        /></Field>
        <Field
          v-if="form.scope === 'targeted'"
          name="msg-recipients"
          :label="tr('recipients')"
          required
          :error="attempted ? issues.recipients : ''"
          ><RemoteSelect
            v-model="form.recipient_ids"
            msg-recipients
            multiple
            name="msg-recipients"
            :label="tr('recipients')"
        /></Field>
        <Field
          name="msg-expiry"
          :label="tr('expiry')"
          :error="attempted ? issues.expiry : ''"
          ><DateTimeField id="msg-expiry" v-model="expiry" name="msg-expiry"
        /></Field>
        <template #feedback
          ><p v-if="sendError" class="form-error" role="alert">
            {{ sendError }}
          </p></template
        >
        <template #actions>
          <t-button :disabled="busy" @click="composeSheet?.requestClose()">{{
            t("cancel")
          }}</t-button>
          <t-button :loading="busy" theme="primary" type="submit">{{
            tr("send")
          }}</t-button>
        </template>
      </EditorForm>
    </Sheet>
    <DiscardSheet v-model="discardOpen" @decide="decide" />
  </section>
</template>
<style scoped>
.msg-status-filter {
  grid-template-columns: repeat(3, 1fr);
}
.msg-read-action {
  justify-content: flex-end;
  padding-bottom: 10px;
}
.msg-content {
  max-height: 384px;
  overflow: auto;
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}
</style>
