// {{ .Project }}/tdesign-vue3-mobile/src/pages/AuthPage.vue
<script setup lang="ts">
import { focusFirstInvalid, message, type Feedback } from '../lib/form-feedback';
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ApiError, acceptSession, loadUser, logout, request, submitCredentials } from '../lib/api';
import type { PointCaptcha as Challenge, CaptchaPoint } from '../lib/types';
import { recordLoginAccount } from '../lib/storage';
import { consumeRegistrationLogin, setRegistrationLogin } from '../lib/registration-login';
import LoginAccountInput from '../components/LoginAccountInput.vue';
import { nonempty, trimCredential } from '../lib/validation';
import { t } from '../locales';
import Field from '../components/Field.vue';
import ServerSlider from '../components/ServerSlider.vue';
import PointCaptcha from '../components/PointCaptcha.vue';
import Copyright from '../components/Copyright.vue';
const route = useRoute();
const router = useRouter();
const mode = computed(() =>
  route.path.endsWith('register')
    ? 'register'
    : route.path.endsWith('reset-password')
      ? 'password_reset'
      : 'login',
);
const username = ref('');
const password = ref('');
const confirmation = ref('');
const proof = ref('');
const slider = ref<InstanceType<typeof ServerSlider>>();
const captcha = ref<Challenge>();
const points = ref<CaptchaPoint[]>([]);
const busy = ref(false);
const errors = ref<Record<string, Feedback>>({});
const formElement = ref<HTMLFormElement>();
const error = ref('');
const notice = ref('');
let noticeTimer: ReturnType<typeof setTimeout> | undefined;
const unavailableUsername = ref('');
const verificationBusy = ref(false);
let verificationGeneration = 0;
let verificationTimer: ReturnType<typeof setTimeout> | undefined;
let verificationController: AbortController | undefined;
function cancelUsernameVerification() {
  verificationGeneration++;
  clearTimeout(verificationTimer);
  verificationTimer = undefined;
  verificationController?.abort();
  verificationController = undefined;
  verificationBusy.value = false;
}
watch(
  username,
  () => {
    cancelUsernameVerification();
    unavailableUsername.value = '';
    captcha.value = undefined;
    points.value = [];
  },
  { flush: 'sync' },
);
watch(
  mode,
  () => {
    cancelUsernameVerification();
    clearTimeout(noticeTimer);
    errors.value = {};
    error.value = '';
    notice.value = '';
    proof.value = '';
    captcha.value = undefined;
    points.value = [];
    confirmation.value = '';
    password.value = '';
    if (mode.value === 'login') {
      const registered = consumeRegistrationLogin();
      if (registered) {
        username.value = registered.username;
        password.value = registered.password;
        notice.value = 'app.register.success';
        noticeTimer = setTimeout(() => {
          notice.value = '';
        }, 5000);
      }
    }
  },
  { immediate: true, flush: 'sync' },
);
onBeforeUnmount(() => {
  clearTimeout(noticeTimer);
  cancelUsernameVerification();
});
async function verifyUsername(account = username.value) {
  cancelUsernameVerification();
  const current = verificationGeneration;
  const value = account.trim();
  if (!value || mode.value === 'password_reset') return;
  const controller = new AbortController();
  verificationController = controller;
  verificationBusy.value = true;
  verificationTimer = setTimeout(() => {
    if (current !== verificationGeneration) return;
    verificationBusy.value = false;
    verificationTimer = undefined;
  }, 5000);
  try {
    if (mode.value === 'register') {
      const result = await request<{ available: boolean }>(
        `/auth/pub/register/username?username=${encodeURIComponent(value)}`,
        { public: true, signal: controller.signal },
      );
      if (current === verificationGeneration) {
        unavailableUsername.value = result.available ? '' : value;
        errors.value.username = result.available ? '' : message('app.register.usernameExists');
      }
    } else {
      const result = await request<{ captcha?: Challenge; captcha_required: boolean }>(
        `/auth/pub/login/verification?username=${encodeURIComponent(value)}`,
        { public: true, signal: controller.signal },
      );
      if (current === verificationGeneration) captcha.value = result.captcha;
    }
  } catch (e) {
    if (current === verificationGeneration) error.value = (e as Error).message;
  } finally {
    if (current === verificationGeneration) {
      clearTimeout(verificationTimer);
      verificationTimer = undefined;
      verificationController = undefined;
      verificationBusy.value = false;
    }
  }
}
async function submit() {
  if (busy.value) return;
  errors.value = {};
  error.value = '';
  const normalizedUsername = trimCredential(username.value);
  const normalizedPassword = trimCredential(password.value);
  const normalizedConfirmation = trimCredential(confirmation.value);
  if (mode.value !== 'password_reset' && !nonempty(normalizedUsername))
    errors.value.username = message('app.validation.username');
  if (
    mode.value === 'register' &&
    unavailableUsername.value &&
    unavailableUsername.value === username.value.trim()
  )
    errors.value.username = message('app.register.usernameExists');
  if (!nonempty(normalizedPassword)) errors.value.password = message('app.validation.password');
  if (mode.value !== 'login' && normalizedConfirmation !== normalizedPassword)
    errors.value.confirmation = message('page.profile.password.passwordMismatch');
  if (mode.value !== 'password_reset' && !captcha.value && !proof.value)
    errors.value.proof = message('app.validation.verification');
  if (captcha.value && !points.value.length)
    errors.value.captcha = message('app.validation.verification');
  if (Object.keys(errors.value).length) {
    await focusFirstInvalid(formElement.value);
    return;
  }
  busy.value = true;
  try {
    if (mode.value === 'register') {
      const available = await request<{ available: boolean }>(
        `/auth/pub/register/username?username=${encodeURIComponent(normalizedUsername)}`,
        { public: true },
      );
      if (!available.available) {
        errors.value.username = message('app.register.usernameExists');
        return;
      }
    }
    const payload =
      mode.value === 'password_reset'
        ? { new_password: normalizedPassword }
        : mode.value === 'register'
          ? {
              username: normalizedUsername,
              password: normalizedPassword,
              slider_proof: proof.value,
            }
          : {
              username: normalizedUsername,
              password: normalizedPassword,
              remember_me: false,
              slider_proof: captcha.value ? undefined : proof.value,
              captcha_id: captcha.value?.captcha_id,
              captcha_points: points.value.length ? points.value : undefined,
            };
    const result = await submitCredentials(mode.value, payload);
    if (mode.value === 'register') {
      setRegistrationLogin(normalizedUsername, normalizedPassword);
      password.value = '';
      confirmation.value = '';
      await router.push('/auth/login');
    } else {
      if (mode.value === 'login' && result.access_token) recordLoginAccount(normalizedUsername);
      acceptSession(result);
      if (result.password_reset_required) {
        await router.replace('/auth/reset-password');
      } else {
        await loadUser();
        const redirect = String(route.query.redirect || '');
        await router.replace(
          redirect.startsWith('/') && !redirect.startsWith('//') && !redirect.startsWith('/auth/')
            ? redirect
            : '/dashboard/overview',
        );
      }
    }
  } catch (e) {
    error.value = (e as Error).message;
    if (e instanceof ApiError && e.data.captcha) {
      captcha.value = e.data.captcha;
      points.value = [];
    }
  } finally {
    busy.value = false;
    slider.value?.reset();
  }
}
</script>
<template>
  <div class="auth-page">
    <section class="auth-panel">
      <h1>
        {{
          mode === 'login'
            ? t('loginTitle')
            : mode === 'register'
              ? t('registerTitle')
              : t('app.resetPassword.title')
        }}
      </h1>
      <p class="lead">
        {{
          mode === 'login'
            ? t('loginHint')
            : mode === 'register'
              ? t('registerHint')
              : t('app.resetPassword.description')
        }}
      </p>
      <form ref="formElement" novalidate @submit.prevent="submit">
        <Field
          v-if="mode !== 'password_reset'"
          name="username"
          :label="t('system.fields.username')"
          :error="errors.username"
          required
          ><LoginAccountInput
            v-if="mode === 'login'"
            v-model="username"
            :loading="verificationBusy"
            @blur="verifyUsername"
            @select="password = ''"
          /><t-input
            v-else
            id="username"
            v-model="username"
            :loading="verificationBusy"
            name="username"
            autocomplete="username"
            :placeholder="t('app.validation.username')"
            @blur="verifyUsername()"
          /> </Field
        ><Field
          name="password"
          :label="
            mode === 'password_reset' ? t('system.fields.newPassword') : t('system.fields.password')
          "
          :error="errors.password"
          required
          ><t-input
            id="password"
            v-model="password"
            name="password"
            type="password"
            autocomplete="new-password"
            :placeholder="t('app.validation.password')" /></Field
        ><Field
          v-if="mode !== 'login'"
          name="confirmation"
          :label="t('page.profile.password.confirmPassword')"
          :error="errors.confirmation"
          required
          ><t-input
            id="confirmation"
            v-model="confirmation"
            name="confirmation"
            type="password"
            autocomplete="new-password"
            :placeholder="t('page.profile.password.confirmPasswordPlaceholder')" /></Field
        ><Field
          v-if="mode !== 'password_reset' && !captcha"
          name="verification"
          :label="t('app.captcha.additional')"
          :error="errors.proof"
          ><ServerSlider
            ref="slider"
            v-model="proof"
            :username="username"
            :password="password"
            :purpose="mode" /></Field
        ><Field
          v-if="captcha"
          name="point-verification"
          :label="t('app.captcha.additional')"
          :error="errors.captcha"
          ><PointCaptcha
            v-model="points"
            :captcha="captcha"
            :username="username"
            @update="captcha = $event"
        /></Field>
        <p v-if="error" class="form-error" role="alert">{{ error }}</p>
        <p v-if="notice" class="notice" role="status">{{ t(notice) }}</p>
        <t-button block theme="primary" type="submit" size="large" :loading="busy">{{
          mode === 'login'
            ? t('page.auth.login')
            : mode === 'register'
              ? t('page.auth.register')
              : t('app.resetPassword.submit')
        }}</t-button
        ><RouterLink
          v-if="mode !== 'password_reset'"
          class="auth-link"
          :to="mode === 'login' ? '/auth/register' : '/auth/login'"
          >{{ mode === 'login' ? t('registerLink') : t('loginLink') }}</RouterLink
        ><button v-else type="button" class="auth-link" @click="logout">{{ t('logout') }}</button>
      </form>
    </section>
    <Copyright />
  </div>
</template>

// {{ .Project }}/ant-design-mobile/src/pages/AuthPage.tsx
import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button } from 'antd-mobile';
import { ApiError, acceptSession, loadUser, logout, request, submitCredentials } from '../lib/api';
import { recordLoginAccount } from '../lib/storage';
import { consumeRegistrationLogin, setRegistrationLogin } from '../lib/registration-login';
import LoginAccountInput from '../components/LoginAccountInput';
import { focusFirstError } from '../lib/form-focus';
import { nonempty } from '../lib/validation';
import { message, type Feedback } from '../lib/form-feedback';
import type { PointCaptcha as Challenge, CaptchaPoint } from '../lib/types';
import { t } from '../locales';
import { Copyright, Field, TextField, ErrorBox } from '../components/UI';
import { ServerSlider, PointCaptcha } from '../components/Captcha';
export default function AuthPage() {
  const location = useLocation(),
    navigate = useNavigate();
  const mode = location.pathname.endsWith('register')
    ? 'register'
    : location.pathname.endsWith('reset-password')
      ? 'password_reset'
      : 'login';
  const [username, setUsername] = useState(''),
    [password, setPassword] = useState(''),
    [confirmation, setConfirmation] = useState(''),
    [proof, setProof] = useState(''),
    [resetKey, setResetKey] = useState(0),
    [captcha, setCaptcha] = useState<Challenge>(),
    [points, setPoints] = useState<CaptchaPoint[]>([]),
    [verificationBusy, setVerificationBusy] = useState(false),
    [busy, setBusy] = useState(false),
    [error, setError] = useState(''),
    [errors, setErrors] = useState<Record<string, Feedback>>({}),
    [registeredNotice, setRegisteredNotice] = useState(
      Boolean((location.state as { registered?: boolean } | null)?.registered),
    );
  const verification = useRef(0);
  const verificationTimer = useRef<number>();
  const verificationController = useRef<AbortController>();
  const formRef = useRef<HTMLFormElement>(null);
  const initializedMode = useRef<typeof mode>();
  function cancelVerification() {
    verification.current++;
    verificationController.current?.abort();
    verificationController.current = undefined;
    window.clearTimeout(verificationTimer.current);
    verificationTimer.current = undefined;
  }
  useLayoutEffect(() => () => cancelVerification(), []);
  useLayoutEffect(() => {
    if (initializedMode.current === mode) return;
    initializedMode.current = mode;
    cancelVerification();
    setPassword('');
    setConfirmation('');
    setProof('');
    setCaptcha(undefined);
    setPoints([]);
    setErrors({});
    setError('');
    setVerificationBusy(false);
    if (mode === 'login') {
      const registered = consumeRegistrationLogin();
      if (registered) {
        setUsername(registered.username);
        setPassword(registered.password);
      }
    }
  }, [mode]);
  useEffect(() => {
    if (!registeredNotice) return;
    navigate(location.pathname, { replace: true, state: null });
    const timer = window.setTimeout(() => setRegisteredNotice(false), 5000);
    return () => window.clearTimeout(timer);
  }, []);
  async function verifyUsername(account = username) {
    cancelVerification();
    const current = verification.current;
    const value = account.trim();
    setVerificationBusy(false);
    if (!value || mode === 'password_reset') return;
    const controller = new AbortController();
    verificationController.current = controller;
    setVerificationBusy(true);
    verificationTimer.current = window.setTimeout(() => {
      if (current !== verification.current) return;
      verificationTimer.current = undefined;
      setVerificationBusy(false);
    }, 5000);
    try {
      if (mode === 'register') {
        const result = await request<{ available: boolean }>(
          `/auth/pub/register/username?username=${encodeURIComponent(value)}`,
          { public: true, signal: controller.signal },
        );
        if (current === verification.current)
          setErrors((e) => ({
            ...e,
            username: result.available ? '' : message('app.register.usernameExists'),
          }));
      } else {
        const result = await request<{ captcha?: Challenge }>(
          `/auth/pub/login/verification?username=${encodeURIComponent(value)}`,
          { public: true, signal: controller.signal },
        );
        if (current === verification.current) setCaptcha(result.captcha);
      }
    } catch (e) {
      if (current === verification.current && !controller.signal.aborted)
        setError((e as Error).message);
    } finally {
      if (current === verification.current) {
        window.clearTimeout(verificationTimer.current);
        verificationTimer.current = undefined;
        verificationController.current = undefined;
        setVerificationBusy(false);
      }
    }
  }
  async function submit() {
    if (busy) return;
    const e: Record<string, Feedback> = {};
    const trimmedUsername = username.trim();
    const trimmedPassword = password.trim();
    const trimmedConfirmation = confirmation.trim();
    setError('');
    if (mode !== 'password_reset' && !nonempty(trimmedUsername))
      e.username = message('app.validation.username');
    if (!nonempty(trimmedPassword)) e.password = message('app.validation.password');
    if (mode !== 'login' && trimmedPassword !== trimmedConfirmation)
      e.confirmation = message('page.profile.password.passwordMismatch');
    if (mode !== 'password_reset' && !captcha && !proof)
      e.proof = message('app.validation.verification');
    if (captcha && !points.length) e.captcha = message('app.validation.verification');
    setErrors(e);
    if (Object.keys(e).length) {
      focusFirstError(formRef.current);
      return;
    }
    setBusy(true);
    try {
      if (mode === 'register') {
        const available = await request<{ available: boolean }>(
          `/auth/pub/register/username?username=${encodeURIComponent(trimmedUsername)}`,
          { public: true },
        );
        if (!available.available) {
          setErrors({ username: message('app.register.usernameExists') });
          return;
        }
      }
      const payload =
        mode === 'password_reset'
          ? { new_password: trimmedPassword }
          : mode === 'register'
            ? { username: trimmedUsername, password: trimmedPassword, slider_proof: proof }
            : {
                username: trimmedUsername,
                password: trimmedPassword,
                remember_me: false,
                slider_proof: captcha ? undefined : proof,
                captcha_id: captcha?.captcha_id,
                captcha_points: points.length ? points : undefined,
              };
      const result = await submitCredentials(mode, payload);
      if (mode === 'register') {
        setRegistrationLogin(trimmedUsername, trimmedPassword);
        setPassword('');
        setConfirmation('');
        navigate('/auth/login', { state: { registered: true } });
        return;
      }
      if (mode === 'login' && result.access_token) recordLoginAccount(trimmedUsername);
      acceptSession(result);
      if (result.password_reset_required) navigate('/auth/reset-password', { replace: true });
      else {
        await loadUser();
        const redirect = new URLSearchParams(location.search).get('redirect') || '';
        navigate(
          redirect.startsWith('/') && !redirect.startsWith('//') && !redirect.startsWith('/auth/')
            ? redirect
            : '/dashboard/overview',
          { replace: true },
        );
      }
    } catch (e) {
      setError((e as Error).message);
      if (e instanceof ApiError && e.data.captcha) {
        setCaptcha(e.data.captcha);
        setPoints([]);
      }
    } finally {
      setBusy(false);
      setResetKey((k) => k + 1);
    }
  }
  return (
    <main id="main" className="auth-page">
      <section className="auth-panel">
        <p className="eyebrow">CINCH · {t('moon')}</p>
        <h1>
          {t(
            mode === 'login'
              ? 'loginTitle'
              : mode === 'register'
                ? 'registerTitle'
                : 'app.resetPassword.title',
          )}
        </h1>
        <p className="lead">
          {t(
            mode === 'login'
              ? 'loginHint'
              : mode === 'register'
                ? 'registerHint'
                : 'app.resetPassword.description',
          )}
        </p>
        <form
          ref={formRef}
          noValidate
          onSubmit={(e) => {
            e.preventDefault();
            void submit();
          }}
        >
          {mode !== 'password_reset' && (
            <>
              {mode === 'login' ? (
                <Field
                  name="username"
                  label={t('system.fields.username')}
                  error={errors.username}
                  required
                >
                  <LoginAccountInput
                    value={username}
                    invalid={!!errors.username}
                    loading={verificationBusy}
                    onChange={(v) => {
                      cancelVerification();
                      setVerificationBusy(false);
                      setUsername(v);
                      setCaptcha(undefined);
                      setPoints([]);
                      setErrors((e) => ({ ...e, username: '' }));
                    }}
                    onBlur={(value) => void verifyUsername(value)}
                    onSelect={() => setPassword('')}
                  />
                </Field>
              ) : (
                <TextField
                  name="username"
                  label={t('system.fields.username')}
                  value={username}
                  loading={verificationBusy}
                  onChange={(v) => {
                    cancelVerification();
                    setVerificationBusy(false);
                    setUsername(v);
                    setCaptcha(undefined);
                    setPoints([]);
                    setErrors((e) => ({ ...e, username: '' }));
                  }}
                  error={errors.username}
                  onBlur={() => void verifyUsername()}
                  required
                />
              )}
            </>
          )}
          <TextField
            name="password"
            label={t(
              mode === 'password_reset' ? 'system.fields.newPassword' : 'system.fields.password',
            )}
            value={password}
            onChange={setPassword}
            type="password"
            autoComplete="new-password"
            error={errors.password}
            required
          />
          {mode !== 'login' && (
            <TextField
              name="confirmation"
              label={t('page.profile.password.confirmPassword')}
              value={confirmation}
              onChange={setConfirmation}
              type="password"
              error={errors.confirmation}
              required
            />
          )}
          {mode !== 'password_reset' && !captcha && (
            <Field name="verification" label={t('app.captcha.additional')} error={errors.proof}>
              <ServerSlider
                username={username}
                purpose={mode}
                proof={proof}
                onProof={setProof}
                resetKey={resetKey}
              />
            </Field>
          )}
          {captcha && (
            <Field
              name="point-verification"
              label={t('app.captcha.additional')}
              error={errors.captcha}
            >
              <PointCaptcha
                captcha={captcha}
                onCaptcha={setCaptcha}
                points={points}
                onPoints={setPoints}
                username={username}
              />
            </Field>
          )}
          <ErrorBox error={error} />
          {registeredNotice && (
            <p className="notice" role="status">
              {t('app.register.success')}
            </p>
          )}
          <Button block color="primary" type="submit" loading={busy}>
            {t(
              mode === 'login'
                ? 'page.auth.login'
                : mode === 'register'
                  ? 'page.auth.register'
                  : 'app.resetPassword.submit',
            )}
          </Button>
          {mode === 'password_reset' ? (
            <button type="button" className="auth-link" onClick={() => void logout()}>
              {t('logout')}
            </button>
          ) : (
            <Link className="auth-link" to={mode === 'login' ? '/auth/register' : '/auth/login'}>
              {t(mode === 'login' ? 'registerLink' : 'loginLink')}
            </Link>
          )}
        </form>
      </section>
      <Copyright />
    </main>
  );
}
