// {{ .Project }}/tdesign-vue3-mobile/src/pages/ManagementPage.vue
<script setup lang="ts">
import { message, type Feedback } from '../lib/form-feedback';
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import dayjs from 'dayjs';
import { can, listResource, saveResource, deleteResources } from '../lib/api';
import type { RecordData, ResourceKind } from '../lib/types';
import { configs } from '../lib/resource-config';
import { dateTime, initials, labelFor, parseDateTime } from '../lib/format';
import { t } from '../locales';
import Icon from '../components/Icon.vue';
import RecordPagination from '../components/RecordPagination.vue';
import ResultToolbar from '../components/ResultToolbar.vue';
import ResultOptions from '../components/ResultOptions.vue';
import Sheet from '../components/Sheet.vue';
import Field from '../components/Field.vue';
import SearchField from '../components/SearchField.vue';
import RecordEditor from '../components/RecordEditor.vue';
import RecordValue from '../components/RecordValue.vue';
import DateTimeField from '../components/DateTimeField.vue';
import PageSkeleton from '../components/PageSkeleton.vue';
import { defaultColumns, identityColumn } from '../lib/resource-presentation';
const props = defineProps<{ resource: ResourceKind }>();
const route = useRoute();
const config = computed(() => configs.value[props.resource]);
const records = ref<RecordData[]>([]);
const total = ref(0);
const page = ref(1);
const size = ref(20);
const loading = ref(false);
const error = ref('');
const notice = ref('');
const filters = ref<Record<string, unknown>>({});
const expanded = ref(false);
const selected = ref<number[]>([]);
const selecting = ref(false);
const primaryFilter = computed(
  () =>
    config.value.filters.find((x) => x.type === 'input') ||
    config.value.filters.find((x) => x.key === 'resource') ||
    config.value.filters[0],
);
const promotedFilterKeys = computed(
  () => new Set([primaryFilter.value.key, ...(props.resource === 'user' ? ['status'] : [])]),
);
const additionalFilters = computed(() =>
  config.value.filters.filter((x) => !promotedFilterKeys.value.has(x.key)),
);
const statuses = computed(() => {
  const value = filters.value.status;
  return (
    Array.isArray(value)
      ? value
      : value === undefined || value === ''
        ? []
        : String(value).split(',')
  )
    .map(Number)
    .filter((item) => [0, 1, 2].includes(item));
});
function statusActive(value: string) {
  return value === 'all' ? !statuses.value.length : statuses.value.includes(Number(value));
}
function selectStatus(value: string) {
  filters.value.status = value === 'all' ? undefined : [Number(value)];
  search();
}
const record = ref<RecordData | null>(null);
const detail = ref(false);
const editor = ref(false);
const options = ref('');
const density = ref('default');
const visibleColumns = ref<string[]>([...defaultColumns[props.resource]]);
const fixedColumn = computed(() => identityColumn[props.resource]);
const hasColumn = (key: string) => visibleColumns.value.includes(key);
const summaryColumns = computed(() => [
  fixedColumn.value,
  ...{
    user: ['role', 'status'],
    role: ['word', 'action_codes'],
    'user-group': ['word', 'users', 'action_codes'],
    action: ['word'],
    dictionary: ['key', 'enabled'],
    whitelist: [],
  }[props.resource],
]);
const extraColumns = computed(() =>
  config.value.columns.filter(
    (column) => hasColumn(column.key) && !summaryColumns.value.includes(column.key),
  ),
);
const recordTitle = (item: RecordData) =>
  props.resource === 'whitelist' ? `#${item.id}` : labelFor(item);

const bordered = ref(false);
const striped = ref(false);
const sticky = ref(true);
const operation = ref('');
const operationOpen = computed({
  get: () => !!operation.value,
  set: (v: boolean) => {
    if (!v) operation.value = '';
  },
});
const busy = ref(false);
const operationError = ref('');
const warning = ref<Feedback>('');
const reason = ref('');
const decision = ref('approve');
const lockMode = ref('until');
const lockUntil = ref('');
const deletion = ref<number[]>([]);
const deletionLabel = ref('');
let generation = 0;
let timer: ReturnType<typeof setTimeout> | undefined;
async function load() {
  if (!can(props.resource, 'read')) return;
  const current = ++generation;
  loading.value = true;
  error.value = '';
  try {
    const result = await listResource(props.resource, {
      ...filters.value,
      p: page.value,
      s: size.value,
    });
    if (current !== generation) return;
    records.value = result.items;
    total.value = result.t;
    selected.value = [];
  } catch (e) {
    if (current === generation) {
      error.value = (e as Error).message;
      records.value = [];
      total.value = 0;
      selected.value = [];
    }
  } finally {
    if (current === generation) loading.value = false;
  }
}
function search() {
  clearTimeout(timer);
  timer = setTimeout(() => {
    page.value = 1;
    void load();
  }, 100);
}
function reset() {
  filters.value = {};
  page.value = 1;
  void load();
}
watch(
  () => route.query,
  () => {
    filters.value = { ...route.query };
    if (route.query.status !== undefined)
      filters.value.status = String(route.query.status).split(',').map(Number);
    page.value = 1;
    void load();
  },
  { immediate: true },
);
function openEditor(item: RecordData | null) {
  if (!can(props.resource, item ? 'update' : 'create')) return;
  record.value = item;
  detail.value = false;
  editor.value = true;
}
function openDetail(item: RecordData) {
  record.value = item;
  detail.value = true;
}
function toggleSelected(id: number) {
  selected.value = selected.value.includes(id)
    ? selected.value.filter((x) => x !== id)
    : [...selected.value, id];
}
function act(value: string) {
  operation.value = value;
  operationError.value = '';
  warning.value = '';
  decision.value = 'approve';
  reason.value = '';
  lockMode.value = 'until';
  lockUntil.value = dateTime(dayjs().add(1, 'day').valueOf());
}
function remove(ids: number[], label = '') {
  deletion.value = ids;
  deletionLabel.value = label;
  act('delete');
}
async function operate() {
  if (busy.value) return;
  operationError.value = '';
  warning.value = '';
  const item = record.value;
  if (operation.value === 'review' && decision.value === 'reject' && !reason.value.trim()) {
    warning.value = message('system.validation.rejectionRequired');
    return;
  }
  const until = parseDateTime(lockUntil.value);
  if (
    operation.value === 'lock' &&
    lockMode.value === 'until' &&
    (!until.isValid() || !until.isAfter(dayjs()))
  ) {
    warning.value = message('system.validation.futureLock');
    return;
  }
  busy.value = true;
  try {
    if (operation.value === 'delete') {
      await deleteResources(props.resource, deletion.value);
      if (records.value.length === deletion.value.length && page.value > 1) page.value--;
    } else if (item) {
      const metadata = { ...item.metadata };
      let status = item.status;
      if (operation.value === 'review') {
        if (decision.value === 'approve') delete metadata.reject_register_reason;
        else metadata.reject_register_reason = reason.value.trim();
        status = decision.value === 'approve' ? 1 : 0;
      }
      if (operation.value === 'lock') {
        metadata.lock_expired_at = lockMode.value === 'permanent' ? 0 : until.valueOf();
        status = 2;
      }
      if (operation.value === 'unlock') {
        delete metadata.lock_expired_at;
        status = 1;
      }
      if (operation.value === 'unlockPassword') delete metadata.password_change_failures;
      await saveResource(
        'user',
        { metadata, ...(operation.value === 'unlockPassword' ? {} : { status }) },
        item.id,
      );
    }
    notice.value = t(
      operation.value === 'delete' ? 'system.messages.deleted' : 'system.messages.updated',
    );
    operation.value = '';
    detail.value = false;
    await load();
  } catch (e) {
    operationError.value = (e as Error).message;
  } finally {
    busy.value = false;
  }
}
function changed() {
  notice.value = t('system.messages.updated');
  void load();
}
onBeforeUnmount(() => {
  generation++;
  clearTimeout(timer);
});
</script>
<template>
  <section
    class="page management"
    :class="[`density-${density}`, { bordered, striped, 'sticky-toolbar': sticky }]"
    :aria-busy="loading"
  >
    <header class="page-heading">
      <RouterLink to="/dashboard/overview?tab=manage" class="back-link" :aria-label="t('manage')">
        <Icon name="chevron-left" :size="22" />
      </RouterLink>
      <div>
        <h1>{{ config.title }}</h1>
      </div>
    </header>
    <template v-if="can(resource, 'read')"
      ><section class="search-region">
        <SearchField
          :key="`${resource}-${primaryFilter.key}`"
          v-model="filters[primaryFilter.key]"
          :field="primaryFilter"
          :resource="resource"
          @search="search"
        />
        <div v-if="resource === 'user'" class="segmented" role="group" :aria-label="t('status')">
          <button
            v-for="value in ['all', '1', '0', '2']"
            :key="value"
            :class="{ active: statusActive(value) }"
            :aria-pressed="statusActive(value)"
            @click="selectStatus(value)"
          >
            {{
              value === 'all'
                ? t('all')
                : t(
                    value === '1'
                      ? 'system.status.active'
                      : value === '0'
                        ? 'system.status.pending'
                        : 'system.status.locked',
                  )
            }}
          </button>
        </div>
        <p v-if="statuses.length > 1" class="filter-status" role="status">
          {{ t('filterMultiStatus', { count: statuses.length }) }}
        </p>
        <div v-if="expanded" class="advanced-filters">
          <SearchField
            v-for="field in additionalFilters"
            :key="field.key"
            v-model="filters[field.key]"
            :field="field"
            :resource="resource"
            @search="search"
          />
        </div>
        <div class="search-actions">
          <button
            class="action-chip action-chip-quiet"
            :aria-expanded="expanded"
            @click="expanded = !expanded"
          >
            <span>{{ t(expanded ? 'system.common.less' : 'system.common.more') }}</span>
            <Icon :name="expanded ? 'chevron-up' : 'chevron-down'" :size="13" /></button
          ><button class="action-chip action-chip-quiet" @click="reset">
            <span>{{ t('system.common.reset') }}</span></button
          ><button class="action-chip action-chip-primary" @click="search">
            <span>{{ t('system.common.search') }}</span>
          </button>
        </div>
      </section>
      <div class="results-region">
        <ResultToolbar @refresh="load" @options="options = $event">
          <button
            v-if="can(resource, 'create')"
            class="create-button create-labeled"
            :aria-label="t('system.common.create')"
            @click="openEditor(null)"
          >
            <Icon name="add" :size="20" /><span>{{ t('system.common.create') }}</span>
          </button>
        </ResultToolbar>
        <div class="selection-tools">
          <div class="selection-actions">
            <button
              v-if="can(resource, 'delete') && records.length"
              class="action-chip action-chip-quiet"
              @click="
                selecting = !selecting;
                selected = [];
              "
            >
              <Icon :name="selecting ? 'check' : 'check-rectangle'" :size="16" />
              <span>{{ t(selecting ? 'done' : 'select') }}</span></button
            ><template v-if="selecting"
              ><button
                class="action-chip action-chip-quiet"
                @click="
                  selected = selected.length === records.length ? [] : records.map((x) => x.id)
                "
              >
                <Icon name="check-double" :size="16" />
                <span>{{ t('system.common.selectAll') }}</span></button
              ><small class="selected-count">{{
                t('selected', { count: selected.length })
              }}</small></template
            ><button
              v-if="selected.length && can(resource, 'delete')"
              class="action-chip action-chip-danger"
              @click="remove([...selected])"
            >
              <Icon name="delete" :size="16" /><span>{{ t('system.common.deleteSelected') }}</span>
            </button>
          </div>
          <span class="result-count">{{ t('system.table.total', { count: total }) }}</span>
        </div>
        <p v-if="notice" class="notice" role="status">{{ notice }}</p>
        <div v-if="error" class="form-error" role="alert">
          {{ error }}<button @click="load">{{ t('retry') }}</button>
        </div>
        <PageSkeleton v-if="loading" variant="list" />
        <div v-else-if="!error" class="card record-list">
          <article
            v-for="item in records"
            :key="item.id"
            class="record-wrap"
            :data-record-id="item.id"
          >
            <div class="record">
              <t-checkbox
                v-if="selecting"
                :checked="selected.includes(item.id)"
                :aria-label="`${t('select')} ${labelFor(item)}`"
                @change="toggleSelected(item.id)"
              /><button
                class="record-open"
                :aria-label="`${t('view')} ${labelFor(item)}`"
                @click="openDetail(item)"
              >
                <span class="avatar"
                  ><Icon
                    v-if="resource !== 'user'"
                    :name="
                      resource === 'role'
                        ? 'secured'
                        : resource === 'action'
                          ? 'key'
                          : resource === 'dictionary'
                            ? 'book'
                            : resource === 'whitelist'
                              ? 'check-rectangle'
                              : 'app'
                    "
                  /><template v-else>{{
                    initials(String(item.metadata?.display_name || item.username || ''))
                  }}</template></span
                >
                <div class="record-main">
                  <strong>{{ recordTitle(item) }}</strong>
                  <small v-if="resource === 'user' && hasColumn('role')">{{
                    item.role?.name || '—'
                  }}</small>
                  <small v-if="resource !== 'user' && hasColumn('word')">{{
                    item.word || '—'
                  }}</small>
                  <small v-if="resource === 'dictionary' && hasColumn('key')">{{ item.key }}</small>
                  <div v-if="['role', 'user-group'].includes(resource)" class="record-summary">
                    <small v-if="resource === 'user-group' && hasColumn('users')">{{
                      t('memberCount', { count: item.users?.length || 0 })
                    }}</small>
                    <small v-if="hasColumn('action_codes')">{{
                      t('permissionSummary', { count: item.action_codes?.length || 0 })
                    }}</small>
                  </div>
                </div>
                <RecordValue
                  v-if="resource === 'user' && hasColumn('status')"
                  :record="item"
                  :column="{ dataIndex: 'status', key: 'status', title: '', display: 'status' }"
                />
                <RecordValue
                  v-if="resource === 'dictionary' && hasColumn('enabled')"
                  :record="item"
                  :column="{ dataIndex: 'enabled', key: 'enabled', title: '', display: 'boolean' }"
                />
                <Icon name="chevron-right" :size="16" />
              </button>
            </div>
            <div v-if="extraColumns.length" class="record-extra">
              <template v-for="column in extraColumns" :key="column.key"
                ><span>{{ column.title }}</span
                ><RecordValue :record="item" :column="column"
              /></template>
            </div>
          </article>
          <t-empty v-if="!records.length" :description="t('noResults')" />
        </div>
        <RecordPagination
          :page="page"
          :size="size"
          :total="total"
          :loading="loading"
          @previous="
            page--;
            load();
          "
          @next="
            page++;
            load();
          "
          @page-size="options = 'pageSize'"
        /></div></template
    ><t-empty v-else :description="t('noAccess')" /><Sheet
      v-model="detail"
      :title="`${config.entity} · ${t('detail')}`"
      ><template v-if="record"
        ><div class="detail-identity">
          <span class="avatar large">{{ initials(labelFor(record)) }}</span>
          <h2>{{ recordTitle(record) }}</h2>
        </div>
        <dl class="details">
          <template v-for="column in config.columns" :key="column.key"
            ><dt>{{ column.title }}</dt>
            <dd><RecordValue :record="record" :column="column" /></dd
          ></template>
        </dl>
        <div class="detail-actions">
          <t-button v-if="can(resource, 'update')" theme="primary" @click="openEditor(record)">{{
            t('system.common.edit')
          }}</t-button
          ><template v-if="resource === 'user' && can(resource, 'update')"
            ><t-button v-if="record.status === 0" variant="outline" @click="act('review')">{{
              t('system.user.review')
            }}</t-button
            ><t-button v-if="record.status === 1" variant="outline" @click="act('lock')">{{
              t('system.user.lock')
            }}</t-button
            ><t-button v-if="record.status === 2" variant="outline" @click="act('unlock')">{{
              t('system.user.unlock')
            }}</t-button
            ><t-button
              v-if="Number(record.metadata?.password_change_failures) > 0"
              variant="outline"
              @click="act('unlockPassword')"
              >{{ t('system.user.unlockPassword') }}</t-button
            ></template
          ><t-button
            v-if="can(resource, 'delete')"
            theme="danger"
            variant="outline"
            @click="remove([record.id], recordTitle(record))"
            >{{ t('system.common.delete') }}</t-button
          >
        </div></template
      ></Sheet
    ><RecordEditor v-model="editor" :resource="resource" :record="record" @saved="changed" /><Sheet
      v-model="operationOpen"
      :title="
        operation === 'delete'
          ? deletionLabel
            ? t('system.confirm.delete', { name: deletionLabel })
            : t('system.confirm.deleteSelected')
          : operation === 'lock'
            ? t('system.user.lockTitle', { name: record ? labelFor(record) : '' })
            : t(`system.user.${operation}`)
      "
      ><form novalidate @submit.prevent="operate">
        <template v-if="operation === 'review'"
          ><Field name="review-decision" :label="t('system.user.decision')"
            ><t-radio-group v-model="decision" class="radio-options"
              ><t-radio :block="false" value="approve" :label="t('system.user.approve')" /><t-radio
                :block="false"
                value="reject"
                :label="t('system.user.reject')" /></t-radio-group></Field
          ><Field
            v-if="decision === 'reject'"
            name="reject-reason"
            :label="t('system.user.reason')"
            :error="warning"
            warning
            ><t-textarea
              id="reject-reason"
              v-model="reason"
              name="reject_reason"
              :placeholder="t('system.user.rejectionPlaceholder')" /></Field></template
        ><template v-else-if="operation === 'lock'"
          ><Field name="lock-mode" :label="t('system.user.lockType')"
            ><t-radio-group v-model="lockMode" class="radio-options"
              ><t-radio :block="false" value="until" :label="t('system.user.lockUntil')" /><t-radio
                :block="false"
                value="permanent"
                :label="t('system.user.permanent')" /></t-radio-group></Field
          ><Field
            v-if="lockMode === 'until'"
            name="lock-until"
            :label="t('system.user.lockedUntil')"
            :error="warning"
            warning
            ><DateTimeField id="lock-until" v-model="lockUntil" name="lock_until" /></Field
        ></template>
        <p v-else>
          {{
            operation === 'delete'
              ? t('system.confirm.deleteDescription', { count: deletion.length })
              : t(`system.confirm.${operation}`, { name: record ? labelFor(record) : '' })
          }}
        </p>
        <p v-if="operationError" class="form-error" role="alert">{{ operationError }}</p>
        <div class="sheet-actions">
          <t-button :disabled="busy" @click="operation = ''">{{ t('cancel') }}</t-button
          ><t-button
            :theme="operation === 'delete' ? 'danger' : 'primary'"
            type="submit"
            :loading="busy"
            >{{ t(operation === 'delete' ? 'system.common.delete' : 'confirm') }}</t-button
          >
        </div>
      </form></Sheet
    ><ResultOptions
      v-model:option="options"
      v-model:density="density"
      v-model:size="size"
      v-model:visible="visibleColumns"
      v-model:bordered="bordered"
      v-model:striped="striped"
      v-model:sticky="sticky"
      :columns="config.columns"
      :fixed-column="fixedColumn"
      @size-change="
        page = 1;
        load();
      "
    />
  </section>
</template>

// {{ .Project }}/ant-design-mobile/src/pages/ManagementPage.tsx
import ResultToolbar from '../components/ResultToolbar';
import RecordPagination from '../components/RecordPagination';
import ResultOptions from '../components/ResultOptions';
import { useEffect, useRef, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Button, Checkbox } from 'antd-mobile';
import { can, listResource } from '../lib/api';
import { configs } from '../lib/resource-config';
import { initials, labelFor } from '../lib/format';
import type { RecordData, ResourceKind } from '../lib/types';
import { t } from '../locales';
import { Icon, IconButton, Sheet, ErrorBox, NoData } from '../components/UI';
import PageSkeleton from '../components/PageSkeleton';
import SearchField from '../components/SearchField';
import RecordEditor from '../components/RecordEditor';
import RecordOperation from '../components/RecordOperation';
import RecordValue from '../components/RecordValue';
import { parseFilters } from '../lib/filters';
import { defaultColumns, identityColumn } from '../lib/resource-presentation';
export default function ManagementPage({ resource }: { resource: ResourceKind }) {
  const config = configs.value[resource],
    location = useLocation();
  const primary =
    config.filters.find((x) => x.type === 'input') ||
    config.filters.find((x) => x.key === 'resource') ||
    config.filters[0];
  const [records, setRecords] = useState<RecordData[]>([]),
    [total, setTotal] = useState(0),
    [page, setPage] = useState(1),
    [size, setSize] = useState(20),
    [loading, setLoading] = useState(true),
    [error, setError] = useState(''),
    [notice, setNotice] = useState(''),
    [filters, setFilters] = useState<Record<string, unknown>>(() =>
      parseFilters(location.search, config.filters),
    ),
    [applied, setApplied] = useState(filters),
    [expanded, setExpanded] = useState(false),
    [selected, setSelected] = useState<number[]>([]),
    [selecting, setSelecting] = useState(false),
    [record, setRecord] = useState<RecordData | null>(null),
    [detail, setDetail] = useState(false),
    [editor, setEditor] = useState(false),
    [options, setOptions] = useState(''),
    [density, setDensity] = useState('default'),
    [filterVersion, setFilterVersion] = useState(0),
    [columns, setColumns] = useState([...defaultColumns[resource]]),
    [bordered, setBordered] = useState(false),
    [striped, setStriped] = useState(false),
    [sticky, setSticky] = useState(true),
    [operation, setOperation] = useState(''),
    [deletion, setDeletion] = useState<number[]>([]),
    [revision, setRevision] = useState(0);
  const timer = useRef<ReturnType<typeof setTimeout>>(),
    filterRef = useRef(filters);
  filterRef.current = filters;
  const resultTop = useRef<HTMLDivElement>(null);
  const scrollToResults = useRef(false);
  const readable = can(resource, 'read');
  const promotedFilterKeys = new Set([primary.key, ...(resource === 'user' ? ['status'] : [])]);
  const additionalFilters = config.filters.filter((f) => !promotedFilterKeys.has(f.key));
  useEffect(() => {
    setFilters(parseFilters(location.search, config.filters));
    setApplied(parseFilters(location.search, config.filters));
    setPage(1);
  }, [location.search]);
  useEffect(() => {
    if (!readable) return;
    let cancelled = false;
    setLoading(true);
    setError('');
    listResource(resource, { ...applied, p: page, s: size })
      .then((result) => {
        if (cancelled) return;
        if (!result.items.length && result.t > 0 && page > 1) {
          setPage((p) => p - 1);
          return;
        }
        setRecords(result.items);
        if (scrollToResults.current) {
          scrollToResults.current = false;
          requestAnimationFrame(() =>
            resultTop.current?.scrollIntoView({ block: 'start', behavior: 'instant' }),
          );
        }
        setTotal(result.t);
        setSelected([]);
      })
      .catch((e) => {
        if (!cancelled) setError(e.message);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [resource, applied, page, size, revision, readable]);
  useEffect(() => () => clearTimeout(timer.current), []);
  function search() {
    clearTimeout(timer.current);
    timer.current = setTimeout(() => {
      setApplied({ ...filterRef.current });
      setPage(1);
    }, 100);
  }
  function changeFilter(key: string, v: unknown) {
    const next = { ...filterRef.current, [key]: v };
    filterRef.current = next;
    setFilters(next);
  }
  function openEditor(r: RecordData | null) {
    if (!can(resource, r ? 'update' : 'create')) return;
    setRecord(r);
    setDetail(false);
    setEditor(true);
  }
  function saved() {
    setNotice(t('system.messages.updated'));
    setDetail(false);
    setRevision((v) => v + 1);
  }
  function remove(ids: number[], r: RecordData | null) {
    setRecord(r);
    setDeletion(ids);
    setOperation('delete');
  }
  const status = Array.isArray(filters.status)
    ? String(filters.status[0])
    : String(filters.status ?? 'all');
  return (
    <section
      className={`page management density-${density} ${bordered ? 'bordered' : ''} ${striped ? 'striped' : ''} ${sticky ? 'sticky-toolbar' : ''}`}
      aria-busy={loading}
    >
      <header className="page-heading">
        <Link to="/dashboard/overview?tab=manage" className="back-link">
          <Icon name="chevron-left" size={16} />
          <span className="sr-only">{t('manage')}</span>
        </Link>

        <div>
          <h1>{config.title}</h1>
        </div>
        <Icon
          name={
            resource === 'user'
              ? 'usergroup'
              : resource === 'role'
                ? 'secured'
                : resource === 'dictionary'
                  ? 'book'
                  : 'app'
          }
          size={28}
        />
      </header>
      {readable ? (
        <>
          <section className="search-region">
            <SearchField
              key={`${resource}-${primary.key}-${filterVersion}`}
              resource={resource}
              field={primary}
              value={filters[primary.key]}
              onChange={(v) => changeFilter(primary.key, v)}
              onSearch={search}
            />
            {resource === 'user' && (
              <div className="segmented status-segmented" role="group" aria-label={t('status')}>
                {['all', '1', '0', '2'].map((value) => (
                  <button
                    key={value}
                    className={status === value ? 'active' : ''}
                    aria-pressed={status === value}
                    onClick={() => {
                      changeFilter('status', value === 'all' ? undefined : [Number(value)]);
                      search();
                    }}
                  >
                    {t(
                      value === 'all'
                        ? 'all'
                        : value === '1'
                          ? 'system.status.active'
                          : value === '0'
                            ? 'system.status.pending'
                            : 'system.status.locked',
                    )}
                  </button>
                ))}
              </div>
            )}
            {expanded && (
              <div className="advanced-filters">
                {additionalFilters.map((f) => (
                  <SearchField
                    key={`${f.key}-${filterVersion}`}
                    resource={resource}
                    field={f}
                    value={filters[f.key]}
                    onChange={(v) => changeFilter(f.key, v)}
                    onSearch={search}
                  />
                ))}
              </div>
            )}
            <div className="search-actions">
              <button
                className="search-toggle"
                aria-expanded={expanded}
                onClick={() => setExpanded((v) => !v)}
              >
                {t(expanded ? 'system.common.less' : 'system.common.more')}
              </button>
              <button
                className="search-reset"
                onClick={() => {
                  filterRef.current = {};
                  setFilters({});
                  setFilterVersion((v) => v + 1);
                  clearTimeout(timer.current);
                  setApplied({});
                  setPage(1);
                }}
              >
                <Icon name="refresh" size={14} />
                <span>{t('system.common.reset')}</span>
              </button>
              <button className="search-submit" onClick={search}>
                <Icon name="search" size={14} />
                <span>{t('system.common.search')}</span>
              </button>
            </div>
          </section>
          {!expanded &&
            Object.entries(applied).some(
              ([key, value]) =>
                !promotedFilterKeys.has(key) && value !== undefined && String(value) !== '',
            ) && (
              <div className="applied-filters" aria-label={t('appliedFilters')}>
                {config.filters
                  .filter(
                    (f) =>
                      !promotedFilterKeys.has(f.key) &&
                      applied[f.key] !== undefined &&
                      String(applied[f.key]) !== '',
                  )
                  .map((f) => {
                    const value = applied[f.key];
                    const values = Array.isArray(value) ? value : [value];
                    const labels = values.map((v) =>
                      f.type.includes('status')
                        ? t(
                            `system.status.${Number(v) === 0 ? 'pending' : Number(v) === 1 ? 'active' : 'locked'}`,
                          )
                        : f.type === 'category'
                          ? t(`system.category.${Number(v) === 0 ? 'permission' : 'jwt'}`)
                          : f.type === 'enabled'
                            ? t(`system.enabled.${String(v) === 'true' ? 'yes' : 'no'}`)
                            : String(v),
                    );
                    return (
                      <button
                        key={f.key}
                        className="resource-tag"
                        aria-label={`${t('clear')} ${f.label}`}
                        onClick={() => {
                          changeFilter(f.key, undefined);
                          search();
                          setFilterVersion((v) => v + 1);
                        }}
                      >
                        {f.label}: {labels.join(' / ')}
                        <Icon name="close" size={14} />
                      </button>
                    );
                  })}
              </div>
            )}
          <div ref={resultTop} className="result-anchor" aria-hidden="true" />
          <div className="results-region">
            <ResultToolbar refresh={() => setRevision((v) => v + 1)} options={setOptions}>
              {can(resource, 'create') && (
                <Button
                  className="create-record"
                  aria-label={t('system.common.create')}
                  size="small"
                  color="primary"
                  onClick={() => openEditor(null)}
                >
                  <Icon name="add" size={16} />
                  <span className="create-label">{t('system.common.create')}</span>
                </Button>
              )}
            </ResultToolbar>
            <div className="selection-tools">
              <div className="selection-actions">
                {can(resource, 'delete') && (records.length > 0 || loading) && (
                  <button
                    className="action-chip action-chip-quiet"
                    disabled={loading}
                    onClick={() => {
                      setSelecting((v) => !v);
                      setSelected([]);
                    }}
                  >
                    <Icon name={selecting ? 'check' : 'check-rectangle'} size={16} />
                    <span>{t(selecting ? 'done' : 'select')}</span>
                  </button>
                )}
                {selecting && (
                  <>
                    <button
                      className="action-chip action-chip-quiet"
                      onClick={() =>
                        setSelected(
                          selected.length === records.length ? [] : records.map((r) => r.id),
                        )
                      }
                    >
                      <Icon name="check-double" size={16} />
                      <span>{t('system.common.selectAll')}</span>
                    </button>
                    <small className="selected-count">
                      {t('selected', { count: selected.length })}
                    </small>
                  </>
                )}
                {selected.length > 0 && can(resource, 'delete') && (
                  <button
                    className="action-chip action-chip-danger"
                    onClick={() => remove([...selected], null)}
                  >
                    <Icon name="delete" size={16} />
                    <span>{t('system.common.deleteSelected')}</span>
                  </button>
                )}
              </div>
              <span className="result-count">{t('system.table.total', { count: total })}</span>
            </div>
            {notice && (
              <p className="notice" role="status">
                {notice}
              </p>
            )}
            <ErrorBox error={error} retry={() => setRevision((v) => v + 1)} />
            {loading ? (
              <PageSkeleton
                variant="list"
                resource={resource}
                rows={records.length || 5}
                selecting={selecting}
                columns={columns}
              />
            ) : records.length ? (
              <div className="card record-list">
                {records.map((r) => (
                  <article className="record-item" data-record-id={r.id} key={r.id}>
                    <div className="record">
                      {selecting && (
                        <Checkbox
                          aria-label={`${t('select')} ${labelFor(r)}`}
                          checked={selected.includes(r.id)}
                          onChange={(checked) =>
                            setSelected((s) =>
                              checked ? [...s, r.id] : s.filter((x) => x !== r.id),
                            )
                          }
                        />
                      )}
                      <button
                        className="record-open"
                        onClick={() => {
                          setRecord(r);
                          setDetail(true);
                        }}
                        aria-label={`${t('view')} ${labelFor(r)}`}
                      >
                        <span className="record-kind">
                          <Icon
                            name={
                              resource === 'user'
                                ? 'user'
                                : resource === 'role'
                                  ? 'secured'
                                  : resource === 'action'
                                    ? 'key'
                                    : resource === 'dictionary'
                                      ? 'book'
                                      : resource === 'whitelist'
                                        ? 'check-rectangle'
                                        : 'usergroup'
                            }
                            size={20}
                          />
                        </span>
                        <span className="record-main">
                          <strong>{labelFor(r)}</strong>
                          <small>
                            {String(
                              r.metadata?.department ||
                                r.role?.name ||
                                r.word ||
                                r.key ||
                                r.code ||
                                `#${r.id}`,
                            )}
                          </small>
                          {(resource === 'role' || resource === 'user-group') && (
                            <small className="record-summary">
                              {resource === 'user-group' &&
                                `${t('memberCount', { count: r.users?.length || 0 })} · `}
                              {t('permissionCount', { count: r.action_codes?.length || 0 })}
                            </small>
                          )}
                          {resource === 'action' && (
                            <small className="record-summary">
                              {String(r.group || '—')} ·{' '}
                              {t('ruleCount', {
                                count: String(r.resource || '')
                                  .split(/\r?\n/)
                                  .filter(Boolean).length,
                              })}
                            </small>
                          )}
                          {resource === 'whitelist' && (
                            <RecordValue
                              record={r}
                              column={{
                                key: 'category',
                                dataIndex: 'category',
                                title: '',
                                display: 'category',
                              }}
                            />
                          )}
                        </span>
                        {r.status !== undefined && (
                          <span className="record-status">
                            <RecordValue
                              record={r}
                              showLockExpiration={false}
                              column={{
                                dataIndex: 'status',
                                key: 'status',
                                title: '',
                                display: 'status',
                              }}
                            />
                          </span>
                        )}
                        {r.enabled !== undefined && (
                          <RecordValue
                            record={r}
                            column={{
                              dataIndex: 'enabled',
                              key: 'enabled',
                              title: '',
                              display: 'boolean',
                            }}
                          />
                        )}
                        <Icon name="chevron-right" size={16} />
                      </button>
                    </div>
                    {columns.some(
                      (key) =>
                        ![
                          identityColumn[resource],
                          ...(resource === 'user'
                            ? ['role', 'status']
                            : resource === 'role'
                              ? ['word', 'action_codes']
                              : resource === 'user-group'
                                ? ['word', 'users', 'action_codes']
                                : resource === 'action'
                                  ? ['word']
                                  : resource === 'dictionary'
                                    ? ['key', 'enabled']
                                    : []),
                        ].includes(key),
                    ) && (
                      <dl className="record-fields">
                        {config.columns
                          .filter(
                            (c) =>
                              columns.includes(c.key) &&
                              c.key !== identityColumn[resource] &&
                              !(
                                resource === 'user'
                                  ? ['role', 'status']
                                  : resource === 'role'
                                    ? ['word', 'action_codes']
                                    : resource === 'user-group'
                                      ? ['word', 'users', 'action_codes']
                                      : resource === 'action'
                                        ? ['word']
                                        : resource === 'dictionary'
                                          ? ['key', 'enabled']
                                          : []
                              ).includes(c.key),
                          )
                          .map((c) => (
                            <div key={c.key}>
                              <dt>{c.title}</dt>
                              <dd>
                                <RecordValue record={r} column={c} />
                              </dd>
                            </div>
                          ))}
                      </dl>
                    )}
                  </article>
                ))}
              </div>
            ) : (
              <NoData text={t('noResults')} />
            )}
            <RecordPagination
              page={page}
              size={size}
              total={total}
              loading={loading}
              change={(value) => {
                scrollToResults.current = true;
                setPage(value);
              }}
              options={() => setOptions('pageSize')}
            />
          </div>
        </>
      ) : (
        <NoData text={t('noAccess')} />
      )}
      <Sheet
        open={detail}
        onClose={() => setDetail(false)}
        title={`${config.entity} · ${t('detail')}`}
        footer={
          record ? (
            <div className="detail-actions">
              {can(resource, 'update') && (
                <Button color="primary" onClick={() => openEditor(record)}>
                  {t('system.common.edit')}
                </Button>
              )}
              {resource === 'user' && can(resource, 'update') && (
                <>
                  <Button
                    onClick={() =>
                      setOperation(
                        record.status === 0 ? 'review' : record.status === 1 ? 'lock' : 'unlock',
                      )
                    }
                  >
                    {t(
                      `system.user.${record.status === 0 ? 'review' : record.status === 1 ? 'lock' : 'unlock'}`,
                    )}
                  </Button>
                  {Number(record.metadata?.password_change_failures) > 0 && (
                    <Button onClick={() => setOperation('unlockPassword')}>
                      {t('system.user.unlockPassword')}
                    </Button>
                  )}
                </>
              )}
              {can(resource, 'delete') && (
                <Button color="danger" fill="outline" onClick={() => remove([record.id], record)}>
                  {t('system.common.delete')}
                </Button>
              )}
            </div>
          ) : undefined
        }
      >
        {record && (
          <>
            <div className="detail-identity">
              <span className="avatar large">{initials(labelFor(record))}</span>
              <h2>{labelFor(record)}</h2>
            </div>
            <dl className="details">
              {config.columns.map((c) => (
                <div
                  className={[
                    c.display === 'json' ||
                    c.display === 'actions' ||
                    c.display === 'users' ||
                    c.display === 'resource-rules' ||
                    ['menu', 'button'].includes(c.key)
                      ? 'detail-wide'
                      : '',
                    c.display === 'status' ? 'detail-status' : '',
                  ]
                    .filter(Boolean)
                    .join(' ')}
                  key={c.key}
                >
                  <dt>{c.title}</dt>
                  <dd>
                    <RecordValue record={record} column={c} />
                  </dd>
                </div>
              ))}
            </dl>
          </>
        )}
      </Sheet>
      {editor && (
        <RecordEditor
          resource={resource}
          record={record}
          onClose={() => setEditor(false)}
          onSaved={saved}
        />
      )}{' '}
      {operation && (
        <RecordOperation
          operation={operation}
          resource={resource}
          record={record}
          ids={deletion}
          onClose={() => setOperation('')}
          onSaved={saved}
        />
      )}
      <ResultOptions
        options={options}
        setOptions={setOptions}
        density={density}
        setDensity={setDensity}
        size={size}
        setSize={setSize}
        setPage={setPage}
        columns={columns}
        setColumns={setColumns}
        fields={config.columns}
        identity={identityColumn[resource]}
        bordered={bordered}
        setBordered={setBordered}
        striped={striped}
        setStriped={setStriped}
        sticky={sticky}
        setSticky={setSticky}
      />
    </section>
  );
}
