// {{ .Project }}/tdesign-vue3-mobile/src/pages/ProfilePage.vue
<script setup lang="ts">
import { focusFirstInvalid, message, type Feedback } from '../lib/form-feedback';
import { onMounted, ref, watch } from 'vue';
import { useUnsavedForm } from '../lib/unsaved-form';
import DiscardSheet from '../components/DiscardSheet.vue';
import { useRoute } from 'vue-router';
import { ApiError, loadUser, logout, session, submitCredentials } from '../lib/api';
import type { CaptchaPoint, PointCaptcha as Challenge } from '../lib/types';
import { initials } from '../lib/format';
import { t } from '../locales';
import { nonempty } from '../lib/validation';
import Icon from '../components/Icon.vue';
import Sheet from '../components/Sheet.vue';
import Field from '../components/Field.vue';
import PointCaptcha from '../components/PointCaptcha.vue';
const route = useRoute();
const infoError = ref('');
const infoLoading = ref(true);
onMounted(async () => {
  try {
    await loadUser();
  } catch (e) {
    infoError.value = (e as Error).message;
  } finally {
    infoLoading.value = false;
  }
});
const passwordOpen = ref(route.query.tab === 'password');
const infoOpen = ref(false);
const confirmLogout = ref(false);
const oldPassword = ref('');
const newPassword = ref('');
const confirmation = ref('');
const errors = ref<Record<string, Feedback>>({});
const formElement = ref<HTMLFormElement>();
const error = ref('');
const busy = ref(false);
const captcha = ref<Challenge>();
const points = ref<CaptchaPoint[]>([]);
const { discardOpen, decide, beforeClose } = useUnsavedForm(
  () => passwordOpen.value && !!(oldPassword.value || newPassword.value || confirmation.value),
  () => passwordOpen.value && busy.value,
);
watch(passwordOpen, (open) => {
  if (!open) {
    oldPassword.value = '';
    newPassword.value = '';
    confirmation.value = '';
    errors.value = {};
    error.value = '';
    captcha.value = undefined;
    points.value = [];
  }
});
async function submit() {
  errors.value = {};
  error.value = '';
  if (!nonempty(oldPassword.value)) errors.value.old = message('app.validation.currentPassword');
  if (!nonempty(newPassword.value)) errors.value.password = message('app.validation.password');
  if (newPassword.value !== confirmation.value)
    errors.value.confirmation = message('page.profile.password.passwordMismatch');
  if (captcha.value && !points.value.length)
    errors.value.captcha = message('app.validation.verification');
  if (Object.keys(errors.value).length) {
    await focusFirstInvalid(formElement.value);
    return;
  }
  busy.value = true;
  try {
    await submitCredentials('password_change', {
      old_password: oldPassword.value,
      new_password: newPassword.value,
      captcha_id: captcha.value?.captcha_id,
      captcha_points: points.value.length ? points.value : undefined,
    });
    passwordOpen.value = false;
    await logout();
  } catch (e) {
    error.value = (e as Error).message;
    if (e instanceof ApiError && e.data.captcha) {
      captcha.value = e.data.captcha;
      points.value = [];
    }
  } finally {
    busy.value = false;
  }
}
</script>
<template>
  <div class="page">
    <p v-if="infoError" class="form-error" role="alert">{{ infoError }}</p>
    <header class="page-heading">
      <div>
        <p class="eyebrow">{{ t('workspace') }}</p>
        <h1>{{ t('mine') }}</h1>
      </div>
    </header>
    <section class="profile-card card" :aria-busy="infoLoading">
      <t-skeleton v-if="infoLoading" animation="gradient" theme="avatar" />
      <template v-else>
        <span class="avatar large">{{ initials(session.user?.username || '') }}</span>
        <h2>{{ session.user?.username }}</h2>
        <p>{{ session.user?.role?.name || '—' }}</p>
        <small class="muted">{{ session.user?.code }}</small>
      </template>
    </section>
    <h2 class="section-title">{{ t('page.auth.profile') }}</h2>
    <section class="card">
      <button class="menu-row" @click="infoOpen = true">
        <Icon name="user" /><span>{{ t('profile') }}</span
        ><Icon name="chevron-right" /></button
      ><button class="menu-row" @click="passwordOpen = true">
        <Icon name="lock-on" /><span>{{ t('password') }}</span
        ><Icon name="chevron-right" />
      </button>
    </section>
    <div class="about">
      <span>Cinch · TDesign Mobile Vue</span><small>{{ t('subtitle') }}</small>
    </div>
    <t-button block variant="outline" theme="danger" @click="confirmLogout = true">{{
      t('logout')
    }}</t-button
    ><Sheet v-model="infoOpen" :title="t('profile')"
      ><dl class="details">
        <dt>{{ t('system.fields.username') }}</dt>
        <dd>{{ session.user?.username }}</dd>
        <dt>{{ t('system.fields.role') }}</dt>
        <dd>{{ session.user?.role?.name || '—' }}</dd>
        <dt>{{ t('system.fields.userCode') }}</dt>
        <dd>{{ session.user?.code }}</dd>
      </dl></Sheet
    ><Sheet v-model="passwordOpen" :before-close="beforeClose" :title="t('password')"
      ><form ref="formElement" novalidate @submit.prevent="submit">
        <Field
          name="old-password"
          :label="t('page.profile.password.oldPassword')"
          :error="errors.old"
          required
          ><t-input
            id="old-password"
            v-model="oldPassword"
            name="old_password"
            type="password"
            autocomplete="current-password" /></Field
        ><Field
          name="new-password"
          :label="t('page.profile.password.newPassword')"
          :error="errors.password"
          required
          ><t-input
            id="new-password"
            v-model="newPassword"
            name="new_password"
            type="password"
            autocomplete="new-password" /></Field
        ><Field
          name="confirm-password"
          :label="t('page.profile.password.confirmPassword')"
          :error="errors.confirmation"
          required
          ><t-input
            id="confirm-password"
            v-model="confirmation"
            name="confirm_password"
            type="password"
            autocomplete="new-password" /></Field
        ><Field
          v-if="captcha"
          name="password-captcha"
          :label="t('app.captcha.additional')"
          :error="errors.captcha"
          ><PointCaptcha
            v-model="points"
            :captcha="captcha"
            authenticated
            @update="captcha = $event"
        /></Field>
        <p v-if="error" role="alert" class="form-error">{{ error }}</p>
        <t-button block theme="primary" type="submit" :loading="busy">{{ t('save') }}</t-button>
      </form></Sheet
    ><Sheet v-model="confirmLogout" :title="t('logoutConfirm')"
      ><div class="sheet-actions">
        <t-button @click="confirmLogout = false">{{ t('cancel') }}</t-button
        ><t-button theme="danger" @click="logout">{{ t('logout') }}</t-button>
      </div></Sheet
    ><DiscardSheet v-model="discardOpen" @decide="decide" />
  </div>
</template>

// {{ .Project }}/ant-design-mobile/src/pages/ProfilePage.tsx
import { useEffect, useRef, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { Button, Skeleton } from 'antd-mobile';
import { ApiError, loadUser, logout, session, submitCredentials } from '../lib/api';
import { focusFirstError } from '../lib/form-focus';
import { nonempty } from '../lib/validation';
import { initials } from '../lib/format';
import type { PointCaptcha as Challenge, CaptchaPoint } from '../lib/types';
import { t } from '../locales';
import { Sheet, Icon, TextField, Field, ErrorBox } from '../components/UI';
import { PointCaptcha } from '../components/Captcha';
export default function ProfilePage() {
  const location = useLocation();
  const formRef = useRef<HTMLFormElement>(null);
  const [panel, setPanel] = useState(
      new URLSearchParams(location.search).get('tab') === 'password' ? 'password' : '',
    ),
    [old, setOld] = useState(''),
    [password, setPassword] = useState(''),
    [confirmation, setConfirmation] = useState(''),
    [errors, setErrors] = useState<Record<string, string>>({}),
    [error, setError] = useState(''),
    [infoError, setInfoError] = useState(''),
    [infoLoading, setInfoLoading] = useState(true),
    [busy, setBusy] = useState(false),
    [captcha, setCaptcha] = useState<Challenge>(),
    [points, setPoints] = useState<CaptchaPoint[]>([]);
  useEffect(() => {
    void loadUser()
      .catch((e) => setInfoError(e.message))
      .finally(() => setInfoLoading(false));
  }, []);
  function closePanel() {
    if (busy) return;
    setPanel('');
    setOld('');
    setPassword('');
    setConfirmation('');
    setErrors({});
    setError('');
    setCaptcha(undefined);
    setPoints([]);
  }
  async function submit() {
    if (busy) return;
    const e: Record<string, string> = {};
    setError('');
    if (!nonempty(old)) e.old = t('app.validation.currentPassword');
    if (!nonempty(password)) e.password = t('app.validation.password');
    if (password !== confirmation) e.confirmation = t('page.profile.password.passwordMismatch');
    if (captcha && !points.length) e.captcha = t('app.validation.verification');
    setErrors(e);
    if (Object.keys(e).length) {
      focusFirstError(formRef.current);
      return;
    }
    setBusy(true);
    try {
      await submitCredentials('password_change', {
        old_password: old,
        new_password: password,
        captcha_id: captcha?.captcha_id,
        captcha_points: points.length ? points : undefined,
      });
      await logout();
    } catch (e) {
      setError((e as Error).message);
      if (e instanceof ApiError && e.data.captcha) {
        setCaptcha(e.data.captcha);
        setPoints([]);
      }
    } finally {
      setBusy(false);
    }
  }
  return (
    <div className="page">
      <header className="page-heading">
        <div>
          <p className="eyebrow">{t('workspace')}</p>
          <h1>{t('mine')}</h1>
          <p className="lead">{t('profileHint')}</p>
        </div>
      </header>
      <ErrorBox error={infoError} />
      <section className="profile-card metal-card" aria-busy={infoLoading}>
        {infoLoading ? (
          <div className="profile-skeleton">
            <Skeleton.Title animated />
            <Skeleton.Title animated />
          </div>
        ) : (
          <>
            <span className="avatar large">{initials(session.user?.username || '')}</span>
            <div>
              <h2>{session.user?.username}</h2>
              <p>{session.user?.role?.name || '—'}</p>
              <small>{session.user?.code}</small>
            </div>
          </>
        )}
      </section>
      <h2 className="section-title">{t('page.auth.profile')}</h2>
      <section className="card">
        {['profile', 'password'].map((key) => (
          <button className="menu-row" key={key} onClick={() => setPanel(key)}>
            <Icon name={key === 'profile' ? 'user' : 'lock-on'} />
            <span>{t(key)}</span>
            <Icon name="chevron-right" size={18} />
          </button>
        ))}
      </section>
      <div className="about">
        <span>Cinch · {t('moon')}</span>
        <small>Ant Design Mobile</small>
      </div>
      <Button block color="danger" fill="outline" onClick={() => setPanel('logout')}>
        {t('logout')}
      </Button>
      <Sheet
        open={!!panel}
        onClose={closePanel}
        busy={busy}
        footer={
          panel === 'password' ? (
            <Button block color="primary" type="submit" form="profile-password-form" loading={busy}>
              {t('save')}
            </Button>
          ) : undefined
        }
        title={t(panel === 'logout' ? 'logoutConfirm' : panel)}
      >
        {panel === 'profile' ? (
          <dl className="details">
            <div>
              <dt>{t('system.fields.username')}</dt>
              <dd>{session.user?.username}</dd>
            </div>
            <div>
              <dt>{t('system.fields.role')}</dt>
              <dd>{session.user?.role?.name || '—'}</dd>
            </div>
            <div>
              <dt>{t('system.fields.userCode')}</dt>
              <dd>{session.user?.code}</dd>
            </div>
          </dl>
        ) : panel === 'logout' ? (
          <div className="sheet-actions">
            <Button onClick={() => setPanel('')}>{t('cancel')}</Button>
            <Button color="danger" onClick={() => void logout()}>
              {t('logout')}
            </Button>
          </div>
        ) : panel === 'password' ? (
          <form
            id="profile-password-form"
            ref={formRef}
            noValidate
            onSubmit={(e) => {
              e.preventDefault();
              void submit();
            }}
          >
            <TextField
              name="old-password"
              label={t('page.profile.password.oldPassword')}
              value={old}
              onChange={setOld}
              type="password"
              autoComplete="current-password"
              error={errors.old}
              required
            />
            <TextField
              name="new-password"
              label={t('page.profile.password.newPassword')}
              value={password}
              onChange={setPassword}
              type="password"
              error={errors.password}
              required
            />
            <TextField
              name="confirm-password"
              label={t('page.profile.password.confirmPassword')}
              value={confirmation}
              onChange={setConfirmation}
              type="password"
              error={errors.confirmation}
              required
            />
            {captcha && (
              <Field
                name="password-captcha"
                label={t('app.captcha.additional')}
                error={errors.captcha}
              >
                <PointCaptcha
                  captcha={captcha}
                  onCaptcha={setCaptcha}
                  points={points}
                  onPoints={setPoints}
                  authenticated
                />
              </Field>
            )}
            <ErrorBox error={error} />
          </form>
        ) : null}
      </Sheet>
    </div>
  );
}
