// {{ .Project }}/vben-antd-vue3/apps/web-antd/src/layouts/msg-bell.vue
<script setup lang="ts">
import type { Msg } from '#/api/msg';

import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';

import { VbenIconButton } from '@vben/common-ui';
import { CircleCheckBig, CircleX } from '@vben/icons';
import { Notification } from '@vben/layouts';
import { useUserStore } from '@vben/stores';
import { formatDateTime } from '@vben/utils';

import { Button, Modal, Spin } from 'ant-design-vue';

import { msgApi, msgChanged } from '#/api/msg';
import { $t } from '#/locales';
import MessageHistory from '#/views/msg/history.vue';

const userStore = useUserStore();
const historyOpen = ref(false);
const popup = ref<InstanceType<typeof Notification>>();
const count = ref<null | number>(null);
const rows = ref<Msg[]>([]);
const open = ref(false);
const loading = ref(false);
const error = ref(false);
const busy = ref(false);
const selected = ref<Msg>();
const detailOpen = ref(false);
const detailLoading = ref(false);
let generation = 0;
let detailGeneration = 0;
let disposed = false;
let timer: ReturnType<typeof setInterval>;

const notifications = computed(() =>
  rows.value.map((item) => ({
    id: item.id,
    avatar: '',
    avatarName: userStore.userInfo?.username || '',
    date: formatDateTime(item.published_at),
    isRead: item.read_at !== null,
    message: item.content,
    title: item.title,
  })),
);

async function refresh() {
  if (disposed || document.hidden || busy.value) return;
  const current = ++generation;
  const loadList = open.value;
  if (loadList) loading.value = true;
  await Promise.all([
    msgApi
      .count()
      .then((result) => {
        if (current === generation) count.value = result.count;
      })
      .catch(() => {
        if (current === generation) count.value = null;
      }),
    ...(loadList
      ? [
          msgApi
            .list(false, { p: 1, s: 10 })
            .then((result) => {
              if (current === generation) {
                rows.value = result.items.slice(0, 10);
                error.value = false;
              }
            })
            .catch(() => {
              if (current === generation) {
                rows.value = [];
                error.value = true;
              }
            }),
        ]
      : []),
  ]);
  if (current === generation) loading.value = false;
}
function onOpenChange(value: boolean) {
  open.value = value;
  if (value) void refresh();
}
async function mutate(action: () => Promise<unknown>) {
  if (busy.value) return;
  busy.value = true;
  generation++;
  try {
    await action();
    msgChanged();
  } finally {
    busy.value = false;
    await refresh();
  }
}
async function markRead(id: number | string) {
  try {
    await mutate(() => msgApi.read(Number(id)));
  } catch {
    // The shared request client presents the localized API error.
  }
}
async function readAll() {
  try {
    await mutate(() => msgApi.readAll());
  } catch {
    /* The request client presents API errors. */
  }
}
function confirmRemove(ids: number[], clear = false) {
  Modal.confirm({
    title: clear ? $t('msg.clearPreviewConfirm', { count: ids.length }) : $t('msg.deleteConfirm'),
    okText: $t('msg.confirm'),
    cancelText: $t('msg.cancel'),
    okButtonProps: { danger: true },
    onOk: () =>
      mutate(async () => {
        for (const id of ids) await msgApi.remove(id, false);
      }),
  });
}
async function openDetail(id: number | string) {
  if (busy.value || loading.value) return;
  const current = ++detailGeneration;
  popup.value?.close();
  selected.value = undefined;
  detailOpen.value = true;
  detailLoading.value = true;
  try {
    const item = await msgApi.get(Number(id), false);
    if (disposed || current !== detailGeneration || !detailOpen.value) return;
    selected.value = item;
    if (item.read_at === null) await mutate(() => msgApi.read(item.id));
  } catch {
    if (current === detailGeneration) detailOpen.value = false;
  } finally {
    if (current === detailGeneration) detailLoading.value = false;
  }
}
watch(detailOpen, (value) => {
  if (!value) detailGeneration++;
});
onMounted(() => {
  void refresh();
  timer = setInterval(refresh, 30000);
  window.addEventListener('cinch-msg-changed', refresh);
  document.addEventListener('visibilitychange', refresh);
});
onBeforeUnmount(() => {
  disposed = true;
  generation++;
  detailGeneration++;
  clearInterval(timer);
  window.removeEventListener('cinch-msg-changed', refresh);
  document.removeEventListener('visibilitychange', refresh);
});
</script>

<template>
  <Notification
    ref="popup"
    :dot="(count ?? 0) > 0"
    :notifications="notifications"
    :disabled="busy || loading || error"
    :trigger-label="$t('msg.inbox')"
    @open-change="onOpenChange"
    @make-all="readAll"
    @clear="
      confirmRemove(
        rows.map((item) => item.id),
        true,
      )
    "
    @on-click="(item) => openDetail(item.id)"
    @view-all="historyOpen = true"
  >
    <template #empty>
      <div v-if="loading" class="flex items-center gap-2" role="status">
        <Spin size="small" />{{ $t('msg.loading') }}
      </div>
      <div v-else-if="error" class="flex flex-col items-center gap-2" role="alert">
        <span>{{ $t('msg.error') }}</span>
        <Button type="link" @click="refresh">{{ $t('msg.retry') }}</Button>
      </div>
      <span v-else>{{ $t('msg.empty') }}</span>
    </template>
    <template #action="{ item }">
      <VbenIconButton
        size="xs"
        variant="ghost"
        class="h-6 w-6 p-0"
        :class="{ 'text-destructive': item.isRead }"
        :disabled="busy || loading"
        :tooltip="$t(item.isRead ? 'msg.delete' : 'msg.markRead')"
        :aria-label="$t(item.isRead ? 'msg.delete' : 'msg.markRead')"
        @click.stop="item.isRead ? confirmRemove([Number(item.id)]) : markRead(item.id)"
      >
        <span class="sr-only">{{ $t(item.isRead ? 'msg.delete' : 'msg.markRead') }}</span>
        <CircleX v-if="item.isRead" class="size-4" />
        <CircleCheckBig v-else class="size-4" />
      </VbenIconButton>
    </template>
  </Notification>
  <MessageHistory v-model:open="historyOpen" />
  <Modal v-model:open="detailOpen" :title="$t('msg.detail')" :width="560" :footer="null">
    <div v-if="detailLoading" class="flex min-h-32 items-center justify-center" role="status">
      <Spin :tip="$t('msg.loading')" />
    </div>
    <template v-else-if="selected">
      <h3 class="mb-2 text-base font-semibold break-words">
        {{ selected.title }}
      </h3>
      <p class="mb-4 text-xs text-muted-foreground">
        {{ formatDateTime(selected.published_at) }}
      </p>
      <p class="max-h-96 overflow-auto whitespace-pre-wrap break-words">
        {{ selected.content }}
      </p>
    </template>
    <div class="mt-4 flex justify-end">
      <Button @click="detailOpen = false">{{ $t('msg.close') }}</Button>
    </div>
  </Modal>
</template>

// {{ .Project }}/shadcn-react/src/features/messages/msg-bell.tsx
"use client";
import { useState } from "react";
import MessagePage from "./message-page";
import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { useAuth } from "@/features/auth/auth-context";
import { useLocale } from "@/features/i18n/locale-context";
import { formatDateTime } from "./date-time";
import { cn } from "@/lib/utils";
import { Icons } from "@/components/icons";
import { useMessages, useUnreadCount } from "./use-messages";
import { useMsgLocale } from "./locale";
export default function MsgBell() {
  const tr = useMsgLocale(),
    count = useUnreadCount(),
    [open, setOpen] = useState(false),
    [historyOpen, setHistoryOpen] = useState(false);
  const auth = useAuth(),
    { timezone } = useLocale();
  const zone =
    timezone === "local"
      ? new Intl.DateTimeFormat().resolvedOptions().timeZone
      : timezone;
  const m = useMessages(false, open);
  return (
    <>
      <Popover open={open} onOpenChange={setOpen}>
        <PopoverTrigger
          render={
            <Button
              className="relative"
              variant="ghost"
              size="icon"
              aria-label={tr("inbox")}
              aria-description={
                (count ?? 0) > 0
                  ? tr("count", { count: count ?? 0 })
                  : undefined
              }
              title={tr("inbox")}
            />
          }
        >
          <Icons.notification />
          {(count ?? 0) > 0 && (
            <span
              className="absolute end-2 top-2 size-2 rounded-full bg-primary"
              data-testid="message-unread-dot"
            />
          )}
        </PopoverTrigger>
        <PopoverContent
          align="end"
          sideOffset={8}
          className="w-max min-w-[min(18rem,calc(100vw-1.5rem))] max-w-[min(25rem,calc(100vw-1.5rem))] overflow-hidden p-0"
        >
          <section
            data-testid="notification-preview"
            aria-label={tr("notifications")}
          >
            <header className="flex items-center justify-between gap-4 px-4 py-3">
              <h2 className="text-sm font-medium">{tr("notifications")}</h2>
              <Button
                variant="ghost"
                size="icon-sm"
                disabled={m.busy || m.loading || !m.total}
                aria-label={tr("readAll")}
                title={tr("readAll")}
                onClick={() => void m.readAll()}
              >
                <Icons.check />
              </Button>
            </header>
            {m.error && (
              <p role="alert" className="px-4 text-sm text-destructive">
                {m.error}
              </p>
            )}
            <ul className="max-h-90 overflow-y-auto">
              {m.rows.map((row) => (
                <li
                  key={row.id}
                  className="grid grid-cols-[40px_minmax(0,1fr)_auto] items-center gap-3 border-t p-3 hover:bg-accent"
                >
                  <div data-testid="notification-avatar" className="self-start">
                    <Avatar size="lg">
                      <AvatarFallback>
                        {auth.user?.username.trim().slice(0, 2).toUpperCase()}
                      </AvatarFallback>
                    </Avatar>
                  </div>
                  <button
                    type="button"
                    aria-label={row.title}
                    disabled={m.busy || m.loading}
                    className="flex min-w-0 flex-col gap-1 text-start"
                    onClick={() => {
                      setOpen(false);
                      void m.openDetail(row);
                    }}
                  >
                    <span
                      data-testid="notification-title"
                      className="block w-full truncate text-sm font-semibold leading-5"
                    >
                      {row.title}
                    </span>
                    <span
                      data-testid="notification-content"
                      className="block w-full truncate text-xs leading-5 text-muted-foreground"
                    >
                      {row.content}
                    </span>
                    <time className="block w-full truncate text-xs leading-5 text-muted-foreground">
                      {formatDateTime(row.published_at, zone)}
                    </time>
                  </button>
                  <Button
                    size="icon-sm"
                    variant="ghost"
                    className={cn("size-6", row.read_at && "text-destructive")}
                    disabled={m.busy || m.loading}
                    aria-label={tr(row.read_at ? "delete" : "markRead")}
                    title={tr(row.read_at ? "delete" : "markRead")}
                    onClick={() =>
                      row.read_at ? m.remove(row) : void m.mark(row)
                    }
                  >
                    {row.read_at ? <Icons.circleX /> : <Icons.circleCheck />}
                  </Button>
                </li>
              ))}
            </ul>
            {!m.rows.length && (
              <p className="flex min-h-36 items-center justify-center px-4 text-sm text-muted-foreground">
                {tr(m.loading ? "loading" : "empty")}
              </p>
            )}
            <footer className="flex items-center justify-between gap-4 border-t px-4 py-3">
              <Button
                size="sm"
                variant="ghost"
                disabled={m.busy || m.loading || !m.rows.length}
                onClick={m.clearPreview}
              >
                {tr("clear")}
              </Button>
              <Button
                size="sm"
                onClick={() => {
                  setOpen(false);
                  setHistoryOpen(true);
                }}
              >
                {tr("viewAll")}
              </Button>
            </footer>
          </section>
        </PopoverContent>
      </Popover>
      <Dialog
        open={m.detail}
        onOpenChange={(v) => {
          if (!v) m.closeDetail();
        }}
      >
        <DialogContent className="max-h-[90vh] overflow-auto sm:max-w-xl">
          <DialogHeader>
            <DialogTitle>{tr("detail")}</DialogTitle>
          </DialogHeader>
          {m.selected && (
            <>
              <h2>{m.selected.title}</h2>
              <p className="text-xs text-muted-foreground">
                {formatDateTime(m.selected.published_at, zone)}
              </p>
              <p className="max-h-96 overflow-auto whitespace-pre-wrap break-words">
                {m.selected.content}
              </p>
            </>
          )}
        </DialogContent>
      </Dialog>
      <Dialog
        open={!!m.confirmation}
        onOpenChange={(v) => {
          if (!v && !m.busy) m.setConfirmation("");
        }}
      >
        <DialogContent showCloseButton={false}>
          <DialogHeader>
            <DialogTitle>{tr("confirm")}</DialogTitle>
          </DialogHeader>
          <p>
            {tr(
              m.confirmation === "clear"
                ? "clearPreviewConfirm"
                : "deleteConfirm",
              { count: m.clearCount },
            )}
          </p>
          <DialogFooter>
            <Button
              variant="outline"
              disabled={m.busy}
              onClick={() => m.setConfirmation("")}
            >
              {tr("cancel")}
            </Button>
            <Button
              disabled={m.busy}
              aria-busy={m.busy}
              onClick={() => void m.confirm()}
            >
              {tr("confirm")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
      {historyOpen && (
        <MessagePage embedded onClose={() => setHistoryOpen(false)} />
      )}
    </>
  );
}
