// {{ .Project }}/tdesign-vue3-mobile/src/components/RecordPagination.vue
<script setup lang="ts">
import Icon from './Icon.vue';
import { t } from '../locales';
defineProps<{ page: number; size: number; total: number; loading: boolean }>();
const emit = defineEmits<{ previous: []; next: []; pageSize: [] }>();
</script>
<template>
  <nav class="pagination" :aria-label="t('page', { page })">
    <button
      type="button"
      class="pagination-button"
      :disabled="page <= 1 || loading"
      @click="emit('previous')"
    >
      <Icon name="chevron-left" :size="16" /><span>{{ t('previous') }}</span>
    </button>
    <div class="page-config">
      <span>{{ t('page', { page }) }}</span
      ><button
        type="button"
        :aria-label="t('pageSize')"
        :disabled="loading"
        @click="emit('pageSize')"
      >
        <span>{{ size }} / {{ t('pageUnit') }}</span
        ><Icon name="chevron-down" :size="13" />
      </button>
    </div>
    <button
      type="button"
      class="pagination-button"
      :disabled="page * size >= total || loading"
      @click="emit('next')"
    >
      <span>{{ t('next') }}</span
      ><Icon name="chevron-right" :size="16" />
    </button>
  </nav>
</template>

// {{ .Project }}/ant-design-mobile/src/components/RecordPagination.tsx
import { t } from '../locales';
import { Icon } from './UI';
export default function RecordPagination({
  page,
  size,
  total,
  loading,
  change,
  options,
}: {
  page: number;
  size: number;
  total: number;
  loading: boolean;
  change: (v: number) => void;
  options: () => void;
}) {
  return (
    <div className="pagination">
      <button
        className="pagination-button"
        disabled={page === 1 || loading}
        onClick={() => change(page - 1)}
      >
        <Icon name="chevron-left" size={16} />
        <span>{t('previous')}</span>
      </button>
      <div className="page-config">
        <span>
          {t('page', { page })} / {Math.max(1, Math.ceil(total / size))}
        </span>
        <button aria-label={t('pageSize')} onClick={options}>
          <span>
            {size} / {t('pageUnit')}
          </span>
          <Icon name="chevron-down" size={13} />
        </button>
      </div>
      <button
        className="pagination-button"
        disabled={page * size >= total || loading}
        onClick={() => change(page + 1)}
      >
        <span>{t('next')}</span>
        <Icon name="chevron-right" size={16} />
      </button>
    </div>
  );
}
