// {{ .Project }}/ant-design-mobile/src/App.tsx
import { lazy, Suspense, useEffect, useRef, useState, useSyncExternalStore } from 'react';
import { Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { subscribe } from 'valtio';
import { Button, ConfigProvider, SearchBar } from 'antd-mobile';
import zhCN from 'antd-mobile/es/locales/zh-CN';
import enUS from 'antd-mobile/es/locales/en-US';
import {
  canMenu,
  getPendingRequests,
  initializeSession,
  session,
  logout,
  subscribePendingRequests,
} from './lib/api';
import { preferences as p } from './lib/preferences';
import { modules } from './lib/navigation';
import { locale, t, toggleLocale } from './locales';
import type { ResourceKind } from './lib/types';
import { Icon, IconButton, Sheet, Copyright, TextField, Loading, NoData } from './components/UI';
import PageSkeleton from './components/PageSkeleton';
import MsgBell from './components/MsgBell';
import Settings, { Choices } from './components/Settings';
const MsgPage = lazy(() => import('./pages/MsgPage'));
const Auth = lazy(() => import('./pages/AuthPage')),
  Overview = lazy(() => import('./pages/OverviewPage')),
  Management = lazy(() => import('./pages/ManagementPage')),
  Profile = lazy(() => import('./pages/ProfilePage'));
let revision = 0;
const listeners = new Set<() => void>();
for (const store of [session, p, locale])
  subscribe(store, () => {
    revision++;
    listeners.forEach((fn) => fn());
  });
const subscribeStores = (fn: () => void) => {
  listeners.add(fn);
  return () => {
    listeners.delete(fn);
  };
};
interface Lock {
  hash: string;
  salt: string;
  userId: number;
}
function readLock(): Lock | null {
  try {
    return JSON.parse(sessionStorage.getItem('cinch-garnet-lock') || 'null');
  } catch {
    return null;
  }
}
async function digest(salt: string, password: string) {
  return [
    ...new Uint8Array(
      await crypto.subtle.digest('SHA-256', new TextEncoder().encode(salt + password)),
    ),
  ]
    .map((x) => x.toString(16).padStart(2, '0'))
    .join('');
}
export default function App() {
  useSyncExternalStore(subscribeStores, () => revision);
  const pendingRequests = useSyncExternalStore(subscribePendingRequests, getPendingRequests);
  const location = useLocation(),
    navigate = useNavigate(),
    auth = location.pathname.startsWith('/auth/');
  const [settings, setSettings] = useState(false),
    [tools, setTools] = useState(false),
    [authTools, setAuthTools] = useState(false),
    [panel, setPanel] = useState(''),
    [query, setQuery] = useState(''),
    [lock, setLock] = useState<Lock | null>(readLock),
    [password, setPassword] = useState(''),
    [lockError, setLockError] = useState(''),
    [initialLoadingExpired, setInitialLoadingExpired] = useState(performance.now() >= 5000);
  const content = useRef<HTMLDivElement>(null);
  function clearLock() {
    setLock(null);
    try {
      sessionStorage.removeItem('cinch-garnet-lock');
    } catch {}
  }
  useEffect(() => {
    void initializeSession();
    const ended = () => {
      clearLock();
      setPanel('');
      navigate('/auth/login', { replace: true });
    };
    const reset = () => navigate('/auth/reset-password', { replace: true });
    window.addEventListener('cinch-session-ended', ended);
    window.addEventListener('cinch-reset-required', reset);
    return () => {
      window.removeEventListener('cinch-session-ended', ended);
      window.removeEventListener('cinch-reset-required', reset);
    };
  }, []);
  useEffect(() => {
    const timer = window.setTimeout(
      () => setInitialLoadingExpired(true),
      Math.max(0, 5000 - performance.now()),
    );
    return () => window.clearTimeout(timer);
  }, []);
  useEffect(() => {
    if (!session.ready || pendingRequests) return;
    let secondFrame = 0;
    const firstFrame = requestAnimationFrame(() => {
      secondFrame = requestAnimationFrame(() => {
        document.querySelector('#app-bootstrap-loading')?.remove();
      });
    });
    return () => {
      cancelAnimationFrame(firstFrame);
      cancelAnimationFrame(secondFrame);
    };
  }, [session.ready, pendingRequests]);
  useEffect(() => {
    setTools(false);
    setAuthTools(false);
    content.current?.scrollTo({ top: 0 });
  }, [location.pathname, location.search, session.ready, session.user?.id]);
  useEffect(() => {
    if (lock && session.user && lock.userId !== session.user.id) clearLock();
  }, [session.user?.id]);
  useEffect(() => {
    const openLock = () => {
      setPassword('');
      setLockError('');
      setPanel('lock');
    };
    window.addEventListener('cinch-lock-screen', openLock);
    return () => window.removeEventListener('cinch-lock-screen', openLock);
  }, []);
  if (!session.ready) return initialLoadingExpired ? <PageSkeleton /> : <Loading />;
  const publicPage = ['/auth/login', '/auth/register'].includes(location.pathname);
  if (!session.accessToken && !publicPage)
    return (
      <Navigate
        to={`/auth/login?redirect=${encodeURIComponent(location.pathname + location.search)}`}
        replace
      />
    );
  if (session.accessToken && session.resetRequired && location.pathname !== '/auth/reset-password')
    return <Navigate to="/auth/reset-password" replace />;
  if (
    session.accessToken &&
    !session.resetRequired &&
    (publicPage || location.pathname === '/auth/reset-password')
  )
    return <Navigate to="/dashboard/overview" replace />;
  if (
    session.accessToken &&
    ((location.pathname.startsWith('/system/') && !canMenu(location.pathname)) ||
      (location.pathname === '/dashboard/workspace' && !canMenu(location.pathname)))
  )
    return <Navigate to="/dashboard/overview?denied=1" replace />;
  const active =
    location.pathname === '/profile'
      ? 'mine'
      : location.pathname.startsWith('/system/')
        ? 'manage'
        : new URLSearchParams(location.search).get('tab') || 'home';
  const go = (tab: string) => {
    navigate(
      tab === 'mine'
        ? '/profile'
        : tab === 'home'
          ? '/dashboard/overview'
          : `/dashboard/overview?tab=${tab}`,
    );
    setPanel('');
  };
  const searchEntries = [
    { path: '/dashboard/overview', label: t('home'), icon: 'home' },
    ...(canMenu('/dashboard/workspace')
      ? [{ path: '/dashboard/workspace', label: t('page.dashboard.workspace'), icon: 'app' }]
      : []),
    ...modules.value,
    { path: '/profile', label: t('page.auth.profile'), icon: 'user' },
  ].filter((x) => x.label.toLowerCase().includes(query.toLowerCase()));
  const routeSkeletonVariant = location.pathname.startsWith('/system/')
    ? 'management'
    : location.pathname.startsWith('/dashboard/')
      ? 'overview'
      : 'page';
  const routes = (
    <Suspense fallback={<PageSkeleton variant={routeSkeletonVariant} />}>
      <Routes>
        <Route path="/" element={<Navigate to="/dashboard/overview" replace />} />
        <Route path="/auth" element={<Navigate to="/auth/login" replace />} />
        <Route path="/dashboard" element={<Navigate to="/dashboard/overview" replace />} />
        {['login', 'register', 'reset-password'].map((mode) => (
          <Route key={mode} path={`/auth/${mode}`} element={<Auth key={mode} />} />
        ))}
        <Route path="/dashboard/overview" element={<Overview />} />
        <Route path="/dashboard/workspace" element={<Overview />} />
        <Route path="/system" element={<Navigate to="/dashboard/overview?tab=manage" replace />} />
        {(
          ['user', 'role', 'user-group', 'action', 'dictionary', 'whitelist'] as ResourceKind[]
        ).map((resource) => (
          <Route
            key={resource}
            path={`/system/${resource}`}
            element={<Management key={resource} resource={resource} />}
          />
        ))}
        <Route path="/msg/inbox" element={<MsgPage key="inbox" />} />
        <Route path="/system/msg" element={<MsgPage key="sent" />} />
        <Route path="/profile" element={<Profile />} />
        <Route
          path="*"
          element={
            <div className="page">
              <NoData text={t('notFound')} />
              <Link to="/dashboard/overview">{t('home')}</Link>
            </div>
          }
        />
      </Routes>
    </Suspense>
  );
  async function setScreenLock() {
    if (!password.trim()) {
      setLockError(t('app.validation.password'));
      return;
    }
    const salt = crypto.randomUUID();
    const value = { salt, hash: await digest(salt, password), userId: session.user!.id };
    setLock(value);
    try {
      sessionStorage.setItem('cinch-garnet-lock', JSON.stringify(value));
    } catch {}
    setPassword('');
    setPanel('');
  }
  async function unlock() {
    if (lock && (await digest(lock.salt, password)) !== lock.hash) {
      setLockError(t('lockWrong'));
      return;
    }
    clearLock();
    setPassword('');
    setLockError('');
  }
  const brand = (
    <Link to="/" className="brand">
      <img src={p.dark ? '/go-cinch-white.svg' : '/go-cinch.svg'} alt="" />
      <span className="brand-wide">Go Cinch Admin by Ant Design Mobile</span>
      <span className="brand-narrow">Go Cinch Admin</span>
      <span className="brand-tiny">Go Cinch</span>
    </Link>
  );
  return (
    <ConfigProvider locale={locale.value === 'zh-CN' ? zhCN : enUS}>
      <a href="#main" className="skip-link">
        {t('home')}
      </a>
      {auth ? (
        <div className="studio auth-studio">
          <div className="device">
            <header className="auth-topbar">
              {brand}
              <div className="auth-tools-wrap">
                <IconButton
                  name={authTools ? 'close' : 'ellipsis'}
                  label={t('more')}
                  expanded={authTools}
                  controls="auth-tools-menu"
                  onClick={() => setAuthTools((value) => !value)}
                />
                {authTools && (
                  <div id="auth-tools-menu" className="auth-tools-menu">
                    <IconButton
                      name="palette"
                      label={t('color')}
                      onClick={() => {
                        setSettings(true);
                        setAuthTools(false);
                      }}
                    />
                    <IconButton
                      name="translate"
                      label={t('language')}
                      onClick={() => {
                        toggleLocale();
                        setAuthTools(false);
                      }}
                    />
                    <IconButton
                      name={p.dark ? 'sunny' : 'moon'}
                      label={t('theme')}
                      onClick={() => {
                        p.dark = !p.dark;
                        setAuthTools(false);
                      }}
                    />
                  </div>
                )}
              </div>
            </header>
            <div className="app-scroll auth-content">{routes}</div>
          </div>
        </div>
      ) : (
        <>
          <div
            className="studio"
            {...(lock ? ({ inert: '' } as Record<string, string>) : {})}
            aria-hidden={!!lock}
          >
            <div className="device">
              <header className="topbar">
                <Link to="/dashboard/overview" className="workspace">
                  <img
                    className="workspace-logo"
                    src={p.dark ? '/go-cinch-white.svg' : '/go-cinch.svg'}
                    alt=""
                  />
                  <span>
                    <strong>Go Cinch</strong>
                    <small>{session.user?.role?.name || t('workspace')}</small>
                  </span>
                </Link>
                <div className="top-tools">
                  <MsgBell />
                  <button
                    className="icon-button"
                    aria-label={t('more')}
                    aria-expanded={tools}
                    onClick={() => setTools((v) => !v)}
                  >
                    <Icon name="ellipsis" />
                  </button>
                </div>
              </header>
              {tools && (
                <>
                  <button
                    className="tools-dismiss"
                    aria-label={t('close')}
                    onClick={() => setTools(false)}
                  />
                  <nav className="shell-tools glass" aria-label={t('more')}>
                    <IconButton
                      name="search"
                      label={t('search')}
                      onClick={() => {
                        setQuery('');
                        setPanel('search');
                      }}
                    />
                    <IconButton
                      name="setting"
                      label={t('settings')}
                      onClick={() => setSettings(true)}
                    />
                    <IconButton name="moon" label={t('theme')} onClick={() => (p.dark = !p.dark)} />
                    <IconButton name="translate" label={t('language')} onClick={toggleLocale} />
                    <IconButton
                      name="time"
                      label={t('timezone')}
                      onClick={() => setPanel('timezone')}
                    />
                    <IconButton
                      name="notification"
                      label={t('app.msg.inbox')}
                      onClick={() => navigate('/msg/inbox')}
                    />
                    <IconButton
                      name="lock-on"
                      label={t('lock')}
                      onClick={() => {
                        setPassword('');
                        setLockError('');
                        setPanel('lock');
                      }}
                    />
                  </nav>
                </>
              )}
              <main ref={content} id="main" className="app-scroll">
                {routes}
                {p.footer && <Copyright />}
              </main>
              <nav className="dock glass" aria-label={t('workspace')}>
                {['home', 'manage', 'security', 'mine'].map((key, i) => (
                  <button
                    key={key}
                    className={active === key ? 'active' : ''}
                    aria-current={active === key ? 'page' : undefined}
                    onClick={() => go(key)}
                  >
                    <Icon name={['home', 'app', 'secured', 'user'][i]} size={20} />
                    <span>{t(key)}</span>
                  </button>
                ))}
              </nav>
            </div>
          </div>
          {lock && (
            <div className="lock-screen">
              <form
                className="auth-panel"
                noValidate
                onSubmit={(e) => {
                  e.preventDefault();
                  void unlock();
                }}
              >
                <Icon name="lock-on" size={38} />
                <h1>{t('lock')}</h1>
                <TextField
                  name="unlock-password"
                  label={t('lockHint')}
                  type="password"
                  value={password}
                  onChange={setPassword}
                  error={lockError}
                />
                <Button block color="primary" type="submit">
                  {t('unlock')}
                </Button>
                <button type="button" className="auth-link" onClick={() => void logout()}>
                  {t('logout')}
                </button>
              </form>
            </div>
          )}
        </>
      )}
      <Sheet
        open={!!panel}
        onClose={() => setPanel('')}
        title={t(panel === 'apps' ? 'allApps' : panel === 'loginPosition' ? 'panel' : panel)}
      >
        {['search', 'apps'].includes(panel) ? (
          <>
            <SearchBar
              className="app-search-bar"
              value={query}
              onChange={setQuery}
              placeholder={t('searchApps')}
              aria-label={t('searchApps')}
            />
            <nav className="app-grid">
              {searchEntries.map((x) => (
                <Link
                  key={x.path}
                  className="app-card card"
                  to={x.path}
                  onClick={() => setPanel('')}
                >
                  <Icon name={x.icon} />
                  <strong>{x.label}</strong>
                </Link>
              ))}
            </nav>
            {!searchEntries.length && <NoData text={t('noResults')} />}
          </>
        ) : panel === 'logout' ? (
          <>
            <p>{t('logoutConfirm')}</p>
            <div className="sheet-actions">
              <Button onClick={() => setPanel('')}>{t('cancel')}</Button>
              <Button color="danger" onClick={() => void logout()}>
                {t('logout')}
              </Button>
            </div>
          </>
        ) : panel === 'loginPosition' ? (
          <>
            <p className="notice">{t('desktopPositionHint')}</p>
            <Choices
              value={p.loginPosition}
              onChange={(v) => (p.loginPosition = String(v))}
              options={['left', 'center', 'right'].map((value) => ({ value, label: t(value) }))}
            />
          </>
        ) : panel === 'timezone' ? (
          <>
            <p className="notice">{t('timezoneHint', { zone: p.timezone })}</p>
            <Choices
              value={p.timezone}
              onChange={(v) => (p.timezone = String(v))}
              options={[
                'Asia/Shanghai',
                'UTC',
                'America/New_York',
                'Europe/London',
                'Asia/Tokyo',
              ].map((value) => ({ value, label: value }))}
            />
          </>
        ) : panel === 'lock' ? (
          <form
            noValidate
            onSubmit={(e) => {
              e.preventDefault();
              void setScreenLock();
            }}
          >
            <TextField
              name="lock-password"
              label={t('lockPassword')}
              value={password}
              onChange={setPassword}
              type="password"
              error={lockError}
            />
            <Button block type="submit" color="primary">
              {t('lock')}
            </Button>
          </form>
        ) : null}
      </Sheet>
      <Settings open={settings} onClose={() => setSettings(false)} showLoginPosition={false} />
    </ConfigProvider>
  );
}

// {{ .Project }}/tdesign-vue3-mobile/src/App.vue
<script setup lang="ts">
import MsgBell from './components/MsgBell.vue';
import { message, type Feedback } from './lib/form-feedback';
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import enUS from 'tdesign-mobile-vue/es/locale/en_US';
import zhCN from 'tdesign-mobile-vue/es/locale/zh_CN';
import { session, logout, canMenu } from './lib/api';
import { modules } from './lib/navigation';
import { preferences as p } from './lib/preferences';
import { locale, t, toggleLocale } from './locales';
import Icon from './components/Icon.vue';
import Sheet from './components/Sheet.vue';
import SettingsSheet from './components/SettingsSheet.vue';
import Copyright from './components/Copyright.vue';
import Field from './components/Field.vue';
import PageSkeleton from './components/PageSkeleton.vue';
import { routeLoading, routeSkeleton } from './router';
const route = useRoute();
const router = useRouter();
const auth = computed(() => route.path.startsWith('/auth/'));
const managementDetail = computed(() => route.path.startsWith('/system/'));
const settings = ref(false);
const authToolsOpen = ref(false);
const authTools = ref<HTMLElement>();
const toolsOpen = ref(false);
const panel = ref('');
const search = ref('');
const routeSkeletonVariant = computed(() => {
  if (route.path.startsWith('/system/')) return 'management';
  if (route.path === '/dashboard/overview' && String(route.query.tab || 'home') === 'home')
    return 'overview';
  if (route.path === '/profile') return 'profile';
  return 'page';
});
function closeAuthTools(event?: Event) {
  if (event && authTools.value?.contains(event.target as Node)) return;
  authToolsOpen.value = false;
}
function authToolsKeyboard(event: KeyboardEvent) {
  if (event.key === 'Escape') closeAuthTools();
}
onMounted(() => {
  document.addEventListener('pointerdown', closeAuthTools);
  document.addEventListener('keydown', authToolsKeyboard);
});
const query = computed(() =>
  [
    { path: '/dashboard/overview', label: t('home'), icon: 'home' },
    ...(canMenu('/dashboard/workspace')
      ? [{ path: '/dashboard/workspace', label: t('page.dashboard.workspace'), icon: 'app' }]
      : []),
    { path: '/msg/inbox', label: t('app.msg.inbox'), icon: 'mail' },
    ...modules.value,
    { path: '/profile', label: t('page.auth.profile'), icon: 'user' },
  ].filter((x) => x.label.toLowerCase().includes(search.value.toLowerCase())),
);
const popup = computed({
  get: () => !!panel.value,
  set: (v: boolean) => {
    if (!v) panel.value = '';
  },
});
watch(
  () => route.fullPath,
  () => {
    toolsOpen.value = false;
    authToolsOpen.value = false;
    void nextTick(() => {
      document.querySelector<HTMLElement>('.device .main')?.scrollTo({ top: 0, left: 0 });
    });
  },
);
const active = computed(() =>
  route.path === '/profile' || route.path === '/msg/inbox'
    ? 'mine'
    : route.path.startsWith('/system/') || route.path === '/dashboard/workspace'
      ? 'manage'
      : String(route.query.tab || 'home'),
);
function navigate(value: string) {
  void router.push(
    value === 'mine'
      ? '/profile'
      : { path: '/dashboard/overview', query: value === 'home' ? {} : { tab: value } },
  );
}
let savedLock: { hash?: string; salt?: string; userId?: number } = {};
try {
  savedLock = JSON.parse(sessionStorage.getItem('cinch-mobile-lock') || '{}');
} catch {
  /* An unavailable browser store leaves locking in memory. */
}
const locked = ref(!!savedLock.hash);
const lockPassword = ref('');
const unlockPassword = ref('');
const lockError = ref<Feedback>('');
let lockHash = savedLock.hash || '';
let lockSalt = savedLock.salt || '';
function clearLock() {
  locked.value = false;
  lockHash = '';
  lockSalt = '';
  savedLock = {};
  try {
    sessionStorage.removeItem('cinch-mobile-lock');
  } catch {
    /* In-memory locking remains available. */
  }
}
watch(
  () => session.user,
  (user) => {
    if (user && savedLock.userId && user.id !== savedLock.userId) clearLock();
  },
);
window.addEventListener('cinch-session-ended', clearLock);
async function digest(value: string) {
  const data = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(lockSalt + value));
  return [...new Uint8Array(data)].map((x) => x.toString(16).padStart(2, '0')).join('');
}
function openLock() {
  panel.value = 'lock';
  lockError.value = '';
}
window.addEventListener('cinch-lock-screen', openLock);
onBeforeUnmount(() => {
  window.removeEventListener('cinch-lock-screen', openLock);
  window.removeEventListener('cinch-session-ended', clearLock);
  document.removeEventListener('pointerdown', closeAuthTools);
  document.removeEventListener('keydown', authToolsKeyboard);
});
async function lock() {
  if (!lockPassword.value.trim()) {
    lockError.value = message('app.validation.password');
    return;
  }
  lockSalt = crypto.randomUUID();
  lockHash = await digest(lockPassword.value);
  savedLock = { hash: lockHash, salt: lockSalt, userId: session.user?.id };
  try {
    sessionStorage.setItem('cinch-mobile-lock', JSON.stringify(savedLock));
  } catch {
    /* Keep the current view locked even without persistent storage. */
  }
  lockPassword.value = '';
  locked.value = true;
  panel.value = '';
}
async function unlock() {
  if ((await digest(unlockPassword.value)) !== lockHash) {
    lockError.value = message('lockWrong');
    return;
  }
  locked.value = false;
  unlockPassword.value = '';
  lockError.value = '';
}
async function signout() {
  panel.value = '';
  clearLock();
  await logout();
}
</script>
<template>
  <t-config-provider :global-config="locale === 'en-US' ? enUS : zhCN"
    ><a href="#main" class="skip-link">{{ t('home') }}</a>
    <div class="ambience" />
    <Transition name="page-loading-fade">
      <div v-if="routeLoading" class="page-loading" role="status" :aria-label="t('loading')">
        <span class="page-loading-orb" aria-hidden="true" />
      </div>
    </Transition>
    <div v-if="auth" class="studio auth-studio">
      <div class="device">
        <header class="auth-topbar">
          <RouterLink to="/" class="brand"
            ><img :src="p.dark ? '/go-cinch-white.svg' : '/go-cinch.svg'" alt="" /><span
              class="brand-wide"
              >Go Cinch Admin by TDesign Mobile Vue</span
            ><span class="brand-narrow">Go Cinch Admin</span
            ><span class="brand-tiny">Go Cinch</span></RouterLink
          >
          <div ref="authTools" class="auth-tools-wrap">
            <button
              class="icon-button"
              :aria-label="t('more')"
              :aria-expanded="authToolsOpen"
              aria-controls="auth-tools-menu"
              @click.stop="authToolsOpen = !authToolsOpen"
            >
              <Icon :name="authToolsOpen ? 'close' : 'ellipsis'" />
            </button>
            <Transition name="auth-tools">
              <div v-if="authToolsOpen" id="auth-tools-menu" class="auth-tools-menu">
                <button
                  :aria-label="t('color')"
                  :title="t('color')"
                  @click="
                    settings = true;
                    closeAuthTools();
                  "
                >
                  <Icon name="palette" />
                </button>
                <button
                  :aria-label="t('language')"
                  :title="t('language')"
                  @click="
                    toggleLocale();
                    closeAuthTools();
                  "
                >
                  <Icon name="translate" />
                </button>
                <button
                  :aria-label="t('theme')"
                  :title="t('theme')"
                  @click="
                    p.dark = !p.dark;
                    closeAuthTools();
                  "
                >
                  <Icon :name="p.dark ? 'sunny' : 'moon'" />
                </button>
              </div>
            </Transition>
          </div>
        </header>
        <main id="main" class="main auth-content">
          <PageSkeleton v-if="routeSkeleton" />
          <RouterView v-else />
        </main>
      </div>
    </div>
    <div v-else class="studio" :inert="locked" :aria-hidden="locked">
      <div class="device">
        <header class="topbar">
          <RouterLink
            v-if="managementDetail"
            to="/dashboard/overview?tab=manage"
            class="shell-back"
            :aria-label="t('manage')"
          >
            <Icon name="chevron-left" :size="20" /><span>{{ t('applicationManagement') }}</span>
          </RouterLink>
          <RouterLink v-else to="/dashboard/overview" class="workspace"
            ><img :src="p.dark ? '/go-cinch-white.svg' : '/go-cinch.svg'" alt="" />
            <div>
              <strong>Go Cinch Admin</strong
              ><small>{{ session.user?.role?.name || t('workspace') }}</small>
            </div></RouterLink
          >
          <div class="top-tools">
            <MsgBell v-if="session.user && !session.resetRequired" />
            <button
              class="icon-button"
              :aria-label="t('more')"
              :aria-expanded="toolsOpen"
              @click="toolsOpen = !toolsOpen"
            >
              <Icon name="ellipsis" />
            </button>
          </div>
        </header>
        <main id="main" class="main">
          <PageSkeleton v-if="routeSkeleton" :variant="routeSkeletonVariant" />
          <RouterView v-else :key="route.path" /><Copyright v-if="p.footer" />
        </main>
        <nav class="bottom-nav glass" :aria-label="t('workspace')">
          <button
            v-for="(icon, key) in {
              home: 'home',
              manage: 'app',
              security: 'secured',
              mine: 'user',
            }"
            :key="key"
            :class="{ active: active === key }"
            :aria-current="active === key ? 'page' : undefined"
            @click="navigate(key)"
          >
            <Icon :name="icon" /><span>{{ t(key) }}</span>
          </button>
        </nav>
      </div>
    </div>
    <Sheet v-model="toolsOpen" :title="t('more')">
      <nav class="shell-tools" :aria-label="t('more')" @click="toolsOpen = false">
        <button @click="panel = 'search'">
          <Icon name="search" /><span>{{ t('search') }}</span>
        </button>
        <button @click="settings = true">
          <Icon name="setting" /><span>{{ t('settings') }}</span>
        </button>
        <button @click="p.dark = !p.dark">
          <Icon :name="p.dark ? 'sunny' : 'moon'" /><span>{{ t('theme') }}</span>
        </button>
        <button @click="toggleLocale">
          <Icon name="translate" /><span>{{ t('language') }}</span>
        </button>
        <button @click="panel = 'timezone'">
          <Icon name="time" /><span>{{ t('timezone') }}</span>
        </button>
        <button @click="openLock">
          <Icon name="lock-on" /><span>{{ t('lock') }}</span>
        </button>
      </nav>
    </Sheet>
    <SettingsSheet v-model="settings" /><Sheet v-model="popup" :title="t(panel)"
      ><template v-if="panel === 'search'"
        ><t-search v-model="search" :placeholder="t('search')" />
        <div v-if="!query.length" class="search-empty" role="status">
          <t-empty :description="t('searchPagesEmpty')" />
          <p class="muted">{{ t('searchPagesHint') }}</p>
          <t-button variant="text" @click="search = ''">{{ t('clear') }}</t-button>
        </div>
        <RouterLink
          v-for="item in query"
          :key="item.path"
          :to="item.path"
          class="menu-row"
          @click="panel = ''"
          ><Icon :name="item.icon" />{{ item.label
          }}<Icon name="chevron-right" /></RouterLink></template
      ><template v-else-if="panel === 'logoutConfirm'"
        ><div class="sheet-actions">
          <t-button @click="panel = ''">{{ t('cancel') }}</t-button
          ><t-button theme="danger" @click="signout">{{ t('logout') }}</t-button>
        </div></template
      ><template v-else-if="panel === 'timezone'"
        ><t-radio-group v-model="p.timezone"
          ><t-radio
            v-for="value in ['Asia/Shanghai', 'Asia/Tokyo', 'Europe/London', 'America/New_York']"
            :key="value"
            :value="value"
            :label="value" /></t-radio-group
      ></template>
      <form v-else-if="panel === 'lock'" novalidate @submit.prevent="lock">
        <Field name="lock-password" :label="t('lockPassword')" :error="lockError"
          ><t-input
            id="lock-password"
            v-model="lockPassword"
            type="password"
            autocomplete="new-password" /></Field
        ><t-button block theme="primary" type="submit">{{ t('lock') }}</t-button>
      </form></Sheet
    >
    <div v-if="locked" class="lock-screen">
      <Icon name="lock-on" :size="44" />
      <h1>{{ t('lock') }}</h1>
      <p>{{ session.user?.username }}</p>
      <form novalidate @submit.prevent="unlock">
        <Field name="unlock-password" :label="t('lockHint')" :error="lockError"
          ><t-input id="unlock-password" v-model="unlockPassword" type="password" /></Field
        ><t-button block theme="primary" type="submit">{{ t('unlock') }}</t-button
        ><button type="button" class="auth-link" @click="signout">{{ t('logout') }}</button>
      </form>
    </div></t-config-provider
  >
</template>
